<?php
/**
 * File containing the ezcWebdavMoveResponse class.
 *
 * @package Webdav
 * @version //autogentag//
 * @copyright Copyright (C) 2005-2007 eZ systems as. All rights reserved.
 * @license http://ez.no/licenses/new_bsd New BSD License
 */
/**
 * Class generated by the backend to respond to MOVE requests.
 *
 * If a {@link ezcWebdavBackend} receives an instance of {@link
 * ezcWebdavMoveRequest} it might react with an instance of {@link
 * ezcWebdavMoveResponse} or with producing an error.
 *
 * @version //autogentag//
 * @package Webdav
 * @copyright Copyright (C) 2005-2007 eZ systems as. All rights reserved.
 * @license http://ez.no/licenses/new_bsd New BSD License
 */
class ezcWebdavMoveResponse extends ezcWebdavCopyResponse
{
}

?>
