<?php
/**
 * File containing the ezcWebdavPropPatchResponse class.
 *
 * @package Webdav
 * @version //autogentag//
 * @copyright Copyright (C) 2005-2009 eZ Systems AS. All rights reserved.
 * @license http://ez.no/licenses/new_bsd New BSD License
 */
/**
 * Class generated by the backend to respond to PROPPATCH requests.
 *
 * If a {@link ezcWebdavBackend} receives an instance of {@link
 * ezcWebdavPropPatchRequest} it might react with an instance of {@link
 * ezcWebdavPropPatchResponse} or with producing an error.
 *
 * @version //autogentag//
 * @package Webdav
 */
class ezcWebdavPropPatchResponse extends ezcWebdavPropFindResponse
{
}

?>
