<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/secure_collection/subdir/untitled folder',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/secure_collection/subdir/untitled folder',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/secure_collection/subdir/untitled%20folder',
  'REDIRECT_URI' => '/index.php/secure_collection/subdir/untitled%20folder',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'MOVE',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'gnome-vfs/2.20.0 neon/0.25.4',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_DESTINATION' => 'http://webdav/secure_collection/subdir/newdir',
  'HTTP_OVERWRITE' => 'F',
  'HTTP_AUTHORIZATION' => 'Digest username="some", realm="eZ Components WebDAV", nonce="91aa3746852cfdd48df93eda53096199", uri="/secure_collection/subdir/untitled%20folder", response="821b6cdb4c17345e8955a12daf403223", algorithm="MD5"',
  'PHP_SELF' => '/index.php/secure_collection/subdir/untitled folder',
  'PHP_AUTH_DIGEST' => 'username="some", realm="eZ Components WebDAV", nonce="91aa3746852cfdd48df93eda53096199", uri="/secure_collection/subdir/untitled%20folder", response="821b6cdb4c17345e8955a12daf403223", algorithm="MD5"',
  'REQUEST_TIME' => 1220431173,
);

?>