<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'CONTENT_LENGTH' => '18803',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/secure_collection/put_test_renamed.xml',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/secure_collection/put_test_renamed.xml',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/secure_collection/put_test_renamed.xml',
  'REDIRECT_URI' => '/index.php/secure_collection/put_test_renamed.xml',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PUT',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'gnome-vfs/2.20.0 neon/0.25.4',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_CONTENT_LENGTH' => '18803',
  'HTTP_AUTHORIZATION' => 'Digest username="some", realm="eZ Components WebDAV", nonce="3fc2a3462c661733bdd3e824196efcf5", uri="/secure_collection/put_test_renamed.xml", response="061df1c09a57805fb63233c5e0e8867c", algorithm="MD5"',
  'PHP_SELF' => '/index.php/secure_collection/put_test_renamed.xml',
  'PHP_AUTH_DIGEST' => 'username="some", realm="eZ Components WebDAV", nonce="3fc2a3462c661733bdd3e824196efcf5", uri="/secure_collection/put_test_renamed.xml", response="061df1c09a57805fb63233c5e0e8867c", algorithm="MD5"',
  'REQUEST_TIME' => 1220431173,
);

?>