<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'CONTENT_LENGTH' => '250',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/secure_collection',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/secure_collection',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/secure_collection',
  'REDIRECT_URI' => '/index.php/secure_collection',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PROPFIND',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'gnome-vfs/2.20.0 neon/0.25.4',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_DEPTH' => '0',
  'HTTP_CONTENT_LENGTH' => '250',
  'CONTENT_TYPE' => 'application/xml',
  'HTTP_AUTHORIZATION' => 'Digest username="some", realm="eZ Components WebDAV", nonce="cd7ca38b1b954b693e116b5040b887b1", uri="/secure_collection", response="fc389d1b537cb8bc5167da64ec021c52", algorithm="MD5"',
  'PHP_SELF' => '/index.php/secure_collection',
  'PHP_AUTH_DIGEST' => 'username="some", realm="eZ Components WebDAV", nonce="cd7ca38b1b954b693e116b5040b887b1", uri="/secure_collection", response="fc389d1b537cb8bc5167da64ec021c52", algorithm="MD5"',
  'REQUEST_TIME' => 1220431173,
);

?>