<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.20',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'CONTENT_LENGTH' => '141',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/secure_collection/lockdir/',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/secure_collection/lockdir/',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/secure_collection/lockdir/',
  'REDIRECT_URI' => '/index.php/secure_collection/lockdir/',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'LOCK',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'cadaver/0.23.2 neon/0.28.3',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_CONTENT_LENGTH' => '141',
  'CONTENT_TYPE' => 'application/xml',
  'HTTP_DEPTH' => 'infinity',
  'HTTP_AUTHORIZATION' => 'Digest username="some", realm="eZ Components WebDAV", nonce="434992dda224c544527d8c816b9f3036", uri="/secure_collection/lockdir/", response="f1e169520cd24e842054ca6a0d99cd93", algorithm="MD5"',
  'PHP_SELF' => '/index.php/secure_collection/lockdir/',
  'PHP_AUTH_DIGEST' => 'username="some", realm="eZ Components WebDAV", nonce="434992dda224c544527d8c816b9f3036", uri="/secure_collection/lockdir/", response="f1e169520cd24e842054ca6a0d99cd93", algorithm="MD5"',
  'REQUEST_TIME' => 1220431173,
);

?>