<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.20',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'CONTENT_LENGTH' => '118',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/secure_collection/newdir/file.txt',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/secure_collection/newdir/file.txt',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/secure_collection/newdir/file.txt',
  'REDIRECT_URI' => '/index.php/secure_collection/newdir/file.txt',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PROPFIND',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'cadaver/0.23.2 neon/0.28.3',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_DEPTH' => '0',
  'HTTP_CONTENT_LENGTH' => '118',
  'CONTENT_TYPE' => 'application/xml',
  'HTTP_AUTHORIZATION' => 'Digest username="some", realm="eZ Components WebDAV", nonce="4f832674eb2b0d1de3267153ebd75919", uri="/secure_collection/newdir/file.txt", response="0f806f0f6a4b1ba67664ac1c2c6b9608", algorithm="MD5"',
  'PHP_SELF' => '/index.php/secure_collection/newdir/file.txt',
  'PHP_AUTH_DIGEST' => 'username="some", realm="eZ Components WebDAV", nonce="4f832674eb2b0d1de3267153ebd75919", uri="/secure_collection/newdir/file.txt", response="0f806f0f6a4b1ba67664ac1c2c6b9608", algorithm="MD5"',
  'REQUEST_TIME' => 1220431173,
);

?>