<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.20',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/secure_collection/nullcollection',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/secure_collection/nullcollection',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/secure_collection/nullcollection',
  'REDIRECT_URI' => '/index.php/secure_collection/nullcollection',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'MOVE',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'cadaver/0.23.2 neon/0.28.3',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_DESTINATION' => 'http://webdav/secure_collection/newdir/collection',
  'HTTP_OVERWRITE' => 'T',
  'HTTP_IF' => '<http://webdav/secure_collection/newdir/> (<opaquelocktoken:e631ab8d-355f-e535-27fa-ddd167cd963f>) <http://webdav/secure_collection/nullcollection> (<opaquelocktoken:6a01b2fc-832e-ebc1-0640-f672c063f13d>)',
  'HTTP_AUTHORIZATION' => 'Digest username="some", realm="eZ Components WebDAV", nonce="4f832674eb2b0d1de3267153ebd75919", uri="/secure_collection/nullcollection", response="d25bc90017044872d3fc20b70bfbca8c", algorithm="MD5"',
  'PHP_SELF' => '/index.php/secure_collection/nullcollection',
  'PHP_AUTH_DIGEST' => 'username="some", realm="eZ Components WebDAV", nonce="4f832674eb2b0d1de3267153ebd75919", uri="/secure_collection/nullcollection", response="d25bc90017044872d3fc20b70bfbca8c", algorithm="MD5"',
  'REQUEST_TIME' => 1220431173,
);

?>