<?php

return array (
  'PWD' => '/',
  'LANG' => 'en_US.UTF-8',
  'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/opt/sun-jdk-1.4.2.17/bin:/opt/sun-jdk-1.4.2.17/jre/bin:/opt/sun-jdk-1.4.2.17/jre/javaws:/usr/kde/3.5/sbin:/usr/kde/3.5/bin:/usr/qt/3/bin:/usr/lib/subversion/bin',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '40589',
  'REMOTE_ADDR' => '127.0.0.1',
  'CONTENT_LENGTH' => '235',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/collection/',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/collection/',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/collection/',
  'REDIRECT_URI' => '/index.php/collection/',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PROPFIND',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_DEPTH' => '1',
  'CONTENT_TYPE' => 'application/xml',
  'HTTP_APPLY_TO_REDIRECT_REF' => 'T',
  'HTTP_USER_AGENT' => 'gvfs/0.2.5',
  'HTTP_CONTENT_LENGTH' => '235',
  'ORIG_SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php/collection/',
  'ORIG_PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs//collection/',
  'PHP_SELF' => '/index.php/collection/',
  'REQUEST_TIME' => 1215449532,
);

?>