<?php
// Autogenerated PersistentObject definition

$def = new ezcPersistentObjectDefinition();
$def->table = 'fileentry';
$def->class = 'FileEntry';

$def->properties['extra']               = new ezcPersistentObjectProperty();
$def->properties['extra']->columnName   = 'extra';
$def->properties['extra']->propertyName = 'extra';
$def->properties['extra']->propertyType = ezcPersistentObjectProperty::PHP_TYPE_STRING;


$def->idProperty               = new ezcPersistentObjectIdProperty();
$def->idProperty->columnName   = 'fid';
$def->idProperty->propertyName = 'id';
$def->idProperty->generator    = new ezcPersistentGeneratorDefinition( 'ezcPersistentManualGenerator' );


$def->properties['name']               = new ezcPersistentObjectProperty();
$def->properties['name']->columnName   = 'name';
$def->properties['name']->propertyName = 'name';
$def->properties['name']->propertyType = ezcPersistentObjectProperty::PHP_TYPE_STRING;


$def->properties['size']               = new ezcPersistentObjectProperty();
$def->properties['size']->columnName   = 'size';
$def->properties['size']->propertyName = 'size';
$def->properties['size']->propertyType = ezcPersistentObjectProperty::PHP_TYPE_INT;


$def->properties['type']               = new ezcPersistentObjectProperty();
$def->properties['type']->columnName   = 'type';
$def->properties['type']->propertyName = 'type';
$def->properties['type']->propertyType = ezcPersistentObjectProperty::PHP_TYPE_INT;

return $def;

?>
