<?php

return array (
  'TERM' => 'xterm',
  'SHELL' => '/bin/bash',
  'DEFAULTLEVEL' => 'default',
  'USER' => 'root',
  'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin',
  'PWD' => '/home/dotxp/web/webdav/htdocs',
  'BOOTLEVEL' => 'boot',
  'SVCNAME' => 'lighttpd',
  'CONSOLETYPE' => 'pty',
  'SHLVL' => '1',
  'HOME' => '/root',
  'SOFTLEVEL' => 'default',
  '_' => '/sbin/start-stop-daemon',
  'PHP_FCGI_CHILDREN' => '1',
  'FCGI_ROLE' => 'RESPONDER',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.18',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '43755',
  'REMOTE_ADDR' => '127.0.0.1',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/litmus/coll/',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs//litmus/coll/',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/litmus/coll/',
  'REDIRECT_URI' => '/index.php/litmus/coll/',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'MKCOL',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'litmus/0.11 neon/0.26.3',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_X_LITMUS' => 'basic: 10 (mkcol_again)',
  'PHP_SELF' => '/index.php/litmus/coll/',
  'REQUEST_TIME' => 1190769208,
  'argv' => 
  array (
  ),
  'argc' => 0,
);

?>