<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '192.168.1.27',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '192.168.1.27',
  'CONTENT_LENGTH' => '380',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/collection',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/collection',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/collection',
  'REDIRECT_URI' => '/index.php/collection',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PROPFIND',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_ACCEPT_LANGUAGE' => 'en-us, de;q=0.5',
  'CONTENT_TYPE' => 'text/xml',
  'HTTP_TRANSLATE' => 'f',
  'HTTP_CONTENT_LENGTH' => '380',
  'HTTP_DEPTH' => '1',
  'HTTP_USER_AGENT' => 'Microsoft Data Access Internet Publishing Provider DAV 1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_CONNECTION' => 'Keep-Alive',
  'HTTP_AUTHORIZATION' => 'Basic c29tZTp0aGluZw==',
  'PHP_SELF' => '/index.php/collection',
  'PHP_AUTH_USER' => 'some',
  'PHP_AUTH_PW' => 'thing',
  'REQUEST_TIME' => 1220431173,
);

?>