<?php
/**
 * File containing the ezcCacheStackMetaDatainterface.
 *
 * @package Cache
 * @version //autogentag//
 * @copyright Copyright (C) 2005-2008 eZ systems as. All rights reserved.
 * @license http://ez.no/licenses/new_bsd New BSD License
 * @filesource
 */

/**
 * Interface for stack meta data.
 *
 * This interface describes the methods that must be supported by a meta data
 * class that is to be used with a {@link ezcCacheStackReplacementStrategy} and
 * therefore used with {@link ezcCacheStackMetaDataStorage::storeMetaData()}
 * and {@link ezcCacheStackMetaDataStorage::restoreMetaData()}.
 * 
 * @package Cache
 * @version //autogen//
 */
interface ezcCacheStackMetaData
{
    /**
     * No-parameter constructor. 
     * 
     * @return void
     */
    public function __construct();

    /**
     * Returns the data data as an array.
     * 
     * @return array
     */
    public function getData();

    /**
     * Sets the intrnal data from the given array $data.
     *
     * The $data array was previously generated by {@link self::getData()}.
     * 
     * @param array $data 
     */
    public function setData( array $data );
}

?>
