<?php

return array (
  'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin',
  'PWD' => '/home/dotxp',
  'HOME' => '/home/dotxp',
  '_' => '/sbin/start-stop-daemon',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.18',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '45203',
  'REMOTE_ADDR' => '127.0.0.1',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/litmus/ccdest/foo.0',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs//litmus/ccdest/foo.0',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/litmus/ccdest/foo.0',
  'REDIRECT_URI' => '/index.php/litmus/ccdest/foo.0',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'DELETE',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'litmus/0.11 neon/0.26.3',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_X_LITMUS' => 'copymove: 7 (copy_coll)',
  'PHP_SELF' => '/index.php/litmus/ccdest/foo.0',
  'REQUEST_TIME' => 1192631983,
);

?>