<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '192.168.1.27',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '192.168.1.27',
  'CONTENT_LENGTH' => '240',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/collection/collection/.svn/text-base/put_test.zip.svn-base',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/collection/collection/.svn/text-base/put_test.zip.svn-base',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/collection/collection/.svn/text-base/put_test.zip.svn-base',
  'REDIRECT_URI' => '/index.php/collection/collection/.svn/text-base/put_test.zip.svn-base',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PROPPATCH',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_TRANSLATE' => 'f',
  'CONTENT_TYPE' => 'text/xml; charset="utf-8"',
  'HTTP_USER_AGENT' => 'Microsoft-WebDAV-MiniRedir/5.1.2600',
  'HTTP_HOST' => 'webdav',
  'HTTP_CONTENT_LENGTH' => '240',
  'HTTP_CONNECTION' => 'Keep-Alive',
  'HTTP_PRAGMA' => 'no-cache',
  'PHP_SELF' => '/index.php/collection/collection/.svn/text-base/put_test.zip.svn-base',
  'REQUEST_TIME' => 1220431173,
);

?>