<?php

return array (
  'TERM' => 'xterm',
  'SHELL' => '/bin/bash',
  'DEFAULTLEVEL' => 'default',
  'USER' => 'root',
  'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin',
  'PWD' => '/home/dotxp/web/webdav/htdocs',
  'BOOTLEVEL' => 'boot',
  'SVCNAME' => 'lighttpd',
  'CONSOLETYPE' => 'pty',
  'SHLVL' => '1',
  'HOME' => '/home/dotxp',
  'SOFTLEVEL' => 'default',
  '_' => '/sbin/start-stop-daemon',
  'PHP_FCGI_CHILDREN' => '1',
  'FCGI_ROLE' => 'RESPONDER',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.18',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '60959',
  'REMOTE_ADDR' => '127.0.0.1',
  'CONTENT_LENGTH' => '250',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/test_collection/baz_coll/baz_1.html',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs//test_collection/baz_coll/baz_1.html',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/test_collection/baz_coll/baz_1.html',
  'REDIRECT_URI' => '/index.php/test_collection/baz_coll/baz_1.html',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PROPFIND',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'gnome-vfs/2.18.1 neon/0.25.4',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_DEPTH' => '0',
  'HTTP_CONTENT_LENGTH' => '250',
  'CONTENT_TYPE' => 'application/xml',
  'PHP_SELF' => '/index.php/test_collection/baz_coll/baz_1.html',
  'REQUEST_TIME' => 1190845889,
  'argv' => 
  array (
  ),
  'argc' => 0,
);

?>