DROP TABLE IF EXISTS `table1`;
CREATE TABLE `table1` (
	`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY
);
DROP TABLE IF EXISTS `table2`;
CREATE TABLE `table2` (
	`id` bigint NOT NULL DEFAULT 0
);
ALTER TABLE `table2` ADD PRIMARY KEY ( `id` );
