<?php

return array (
  'PWD' => '/',
  'LANG' => 'en_US.UTF-8',
  'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/opt/sun-jdk-1.4.2.17/bin:/opt/sun-jdk-1.4.2.17/jre/bin:/opt/sun-jdk-1.4.2.17/jre/javaws:/usr/kde/3.5/sbin:/usr/kde/3.5/bin:/usr/qt/3/bin:/usr/lib/subversion/bin',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '37845',
  'REMOTE_ADDR' => '127.0.0.1',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/collection/uploaded/put_test_utf8_content.txt',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/collection/uploaded/put_test_utf8_content.txt',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/collection/uploaded/put_test_utf8_content.txt',
  'REDIRECT_URI' => '/index.php/collection/uploaded/put_test_utf8_content.txt',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'GET',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'cadaver/0.23.2 neon/0.28.2',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'ORIG_SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php/collection/uploaded/put_test_utf8_content.txt',
  'ORIG_PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs//collection/uploaded/put_test_utf8_content.txt',
  'PHP_SELF' => '/index.php/collection/uploaded/put_test_utf8_content.txt',
  'REQUEST_TIME' => 1215459510,
);

?>