<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.20',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'CONTENT_LENGTH' => '740',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/collection/subdir/put_test_utf8_content.txt',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/collection/subdir/put_test_utf8_content.txt',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/collection/subdir/put_test_utf8_content.txt',
  'REDIRECT_URI' => '/index.php/collection/subdir/put_test_utf8_content.txt',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PUT',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'BitKinex/3.0.2',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_PRAGMA' => 'no-cache',
  'HTTP_CACHE_CONTROL' => 'no-cache',
  'HTTP_CONTENT_LENGTH' => '740',
  'CONTENT_TYPE' => 'application/octet-stream',
  'HTTP_TRANSLATE' => 'f',
  'PHP_SELF' => '/index.php/collection/subdir/put_test_utf8_content.txt',
  'REQUEST_TIME' => 1220431173,
);

?>