<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.20',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'CONTENT_LENGTH' => '220',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/secure_collection/subdir/newdir/newsubdir/',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/secure_collection/subdir/newdir/newsubdir/',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/secure_collection/subdir/newdir/newsubdir/',
  'REDIRECT_URI' => '/index.php/secure_collection/subdir/newdir/newsubdir/',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PROPFIND',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'BitKinex/3.0.2',
  'HTTP_ACCEPT' => '*/*',
  'HTTP_PRAGMA' => 'no-cache',
  'HTTP_CACHE_CONTROL' => 'no-cache',
  'HTTP_DEPTH' => '1',
  'HTTP_CONTENT_LENGTH' => '220',
  'CONTENT_TYPE' => 'text/xml',
  'HTTP_AUTHORIZATION' => 'Digest username="some", realm="eZ Components WebDAV", nonce="ef3b75da8f0b48c9e277c19d6dea6aec", uri="/secure_collection/subdir/newdir/newsubdir/", qop=, nc=00000001, cnonce="11f733ec", response="c910c1009bada75751fe047a36ae7313"',
  'PHP_SELF' => '/index.php/secure_collection/subdir/newdir/newsubdir/',
  'PHP_AUTH_DIGEST' => 'username="some", realm="eZ Components WebDAV", nonce="ef3b75da8f0b48c9e277c19d6dea6aec", uri="/secure_collection/subdir/newdir/newsubdir/", qop=, nc=00000001, cnonce="11f733ec", response="c910c1009bada75751fe047a36ae7313"',
  'REQUEST_TIME' => 1220431173,
);

?>