<?php
// Autogenerated class file

/**
 * Data class ce_message_category_rel.
 * Class to be used with eZ Components PersistentObject.
 */
class ezcappce_message_category_rel
{
    /**
     * category_id
     *
     * @var int
     */
    private $category_id;
    /**
     * is_shadow
     *
     * @var 
     */
    private $is_shadow;
    /**
     * message_id
     *
     * @var int
     */
    private $message_id;

    /**
     * Set the PersistentObject state.
     *
     * @param array(string=>mixed) $state The state to set.
     * @return void
     */
     public function setState( array $state )
     {
         foreach ( $state as $attribute => $value )
         {
             $this->$attribute = $value;
         }
     }

    /**
     * Get the PersistentObject state.
     *
     * @return array(string=>mixed) The state of the object.
     */
     public function getState()
     {
         return array(
             'category_id' => $this->category_id,
             'is_shadow' => $this->is_shadow,
             'message_id' => $this->message_id,
         );
     }
}
?>
