<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'CONTENT_LENGTH' => '288',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/collection/subdir/',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/collection/subdir/',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/collection/subdir/',
  'REDIRECT_URI' => '/index.php/collection/subdir/',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PROPFIND',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'cadaver/0.23.2 neon/0.28.3',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_DEPTH' => '1',
  'HTTP_CONTENT_LENGTH' => '288',
  'CONTENT_TYPE' => 'application/xml',
  'PHP_SELF' => '/index.php/collection/subdir/',
  'REQUEST_TIME' => 1220431173,
);

?>