<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/secure_collection/subdir/put_test_utf8_content.txt',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/secure_collection/subdir/put_test_utf8_content.txt',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/secure_collection/subdir/put_test_utf8_content.txt',
  'REDIRECT_URI' => '/index.php/secure_collection/subdir/put_test_utf8_content.txt',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'MOVE',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'cadaver/0.23.2 neon/0.28.3',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_DESTINATION' => 'http://webdav/secure_collection/subdir/put_test_%c3%b6%c3%a4%c3%bc%c3%9f.txt',
  'HTTP_OVERWRITE' => 'T',
  'HTTP_AUTHORIZATION' => 'Digest username="some", realm="eZ Components WebDAV", nonce="2afa2418d6217f61d9c0ede2b38ffd26", uri="/secure_collection/subdir/put_test_utf8_content.txt", response="928efffa117c6211c7bb864b1d3a76ab", algorithm="MD5"',
  'PHP_SELF' => '/index.php/secure_collection/subdir/put_test_utf8_content.txt',
  'PHP_AUTH_DIGEST' => 'username="some", realm="eZ Components WebDAV", nonce="2afa2418d6217f61d9c0ede2b38ffd26", uri="/secure_collection/subdir/put_test_utf8_content.txt", response="928efffa117c6211c7bb864b1d3a76ab", algorithm="MD5"',
  'REQUEST_TIME' => 1220431173,
);

?>