<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'CONTENT_LENGTH' => '14013',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/secure_collection/subdir/collection/put_test.xml',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/secure_collection/subdir/collection/put_test.xml',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/secure_collection/subdir/collection/put_test.xml',
  'REDIRECT_URI' => '/index.php/secure_collection/subdir/collection/put_test.xml',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PUT',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'cadaver/0.23.2 neon/0.28.3',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_CONTENT_LENGTH' => '14013',
  'HTTP_AUTHORIZATION' => 'Digest username="some", realm="eZ Components WebDAV", nonce="2afa2418d6217f61d9c0ede2b38ffd26", uri="/secure_collection/subdir/collection/put_test.xml", response="eb9bf04d827c8ae161fb572827a0f40b", algorithm="MD5"',
  'PHP_SELF' => '/index.php/secure_collection/subdir/collection/put_test.xml',
  'PHP_AUTH_DIGEST' => 'username="some", realm="eZ Components WebDAV", nonce="2afa2418d6217f61d9c0ede2b38ffd26", uri="/secure_collection/subdir/collection/put_test.xml", response="eb9bf04d827c8ae161fb572827a0f40b", algorithm="MD5"',
  'REQUEST_TIME' => 1220431173,
);

?>