<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/collection_renamed/',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/collection_renamed/',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/collection_renamed/',
  'REDIRECT_URI' => '/index.php/collection_renamed/',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PROPFIND',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'cadaver/0.23.2 neon/0.28.3',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_DEPTH' => '0',
  'HTTP_CONTENT_LENGTH' => '288',
  'HTTP_AUTHORIZATION' => 'Digest username="some", realm="eZ Components WebDAV", nonce="1b8e053e2aa14acc11e8d6d63ab34232", uri="/collection_renamed/", response="44634e13d38df1e1b367a0db2c9e4cd4", algorithm="MD5"',
  'PHP_SELF' => '/index.php/collection_renamed/',
  'PHP_AUTH_DIGEST' => 'username="some", realm="eZ Components WebDAV", nonce="1b8e053e2aa14acc11e8d6d63ab34232", uri="/collection_renamed/", response="44634e13d38df1e1b367a0db2c9e4cd4", algorithm="MD5"',
  'REQUEST_TIME' => 1220431173,
);

?>