<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.20',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/secure_collection/subdir/put_test_öäüß.txt',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/secure_collection/subdir/put_test_öäüß.txt',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/secure_collection/subdir/put_test_%C3%B6%C3%A4%C3%BC%C3%9F.txt',
  'REDIRECT_URI' => '/index.php/secure_collection/subdir/put_test_öäüß.txt',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'MOVE',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.10 (like Gecko) (Gentoo)',
  'HTTP_PRAGMA' => 'no-cache',
  'HTTP_CACHE_CONTROL' => 'no-cache',
  'HTTP_ACCEPT' => 'text/html, image/jpeg, image/png, text/*, image/*, */*',
  'HTTP_ACCEPT_ENCODING' => 'x-gzip, x-deflate, gzip, deflate',
  'HTTP_ACCEPT_CHARSET' => 'utf-8, utf-8;q=0.5, *;q=0.5',
  'HTTP_ACCEPT_LANGUAGE' => 'en',
  'HTTP_HOST' => 'webdav',
  'HTTP_AUTHORIZATION' => 'Digest username="some", realm="eZ Components WebDAV", nonce="a5ad137da9f5ce2b7ba5e26a053333db", uri="/secure_collection/subdir/put_test_%C3%B6%C3%A4%C3%BC%C3%9F.txt", algorithm="MD5", response="0e4e8fadea3f818fd169da23230907f3"',
  'HTTP_CONNECTION' => 'Keep-Alive',
  'HTTP_DESTINATION' => 'http://webdav/secure_collection/put_test_%C3%B6%C3%A4%C3%BC%C3%9F.txt',
  'HTTP_DEPTH' => 'infinity',
  'HTTP_OVERWRITE' => 'F',
  'PHP_SELF' => '/index.php/secure_collection/subdir/put_test_öäüß.txt',
  'PHP_AUTH_DIGEST' => 'username="some", realm="eZ Components WebDAV", nonce="a5ad137da9f5ce2b7ba5e26a053333db", uri="/secure_collection/subdir/put_test_%C3%B6%C3%A4%C3%BC%C3%9F.txt", algorithm="MD5", response="0e4e8fadea3f818fd169da23230907f3"',
  'REQUEST_TIME' => 1220431173,
);

?>