<?php

return array (
  'PWD' => '/',
  'LANG' => 'en_US.UTF-8',
  'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/opt/sun-jdk-1.4.2.17/bin:/opt/sun-jdk-1.4.2.17/jre/bin:/opt/sun-jdk-1.4.2.17/jre/javaws:/usr/kde/3.5/sbin:/usr/kde/3.5/bin:/usr/qt/3/bin:/usr/lib/subversion/bin',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '54345',
  'REMOTE_ADDR' => '127.0.0.1',
  'CONTENT_LENGTH' => '303',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/',
  'REDIRECT_URI' => '/index.php/',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PROPFIND',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.9 (like Gecko) (Gentoo)',
  'HTTP_PRAGMA' => 'no-cache',
  'HTTP_CACHE_CONTROL' => 'no-cache',
  'HTTP_ACCEPT' => 'text/html, image/jpeg, image/png, text/*, image/*, */*',
  'HTTP_ACCEPT_ENCODING' => 'x-gzip, x-deflate, gzip, deflate',
  'HTTP_ACCEPT_CHARSET' => 'utf-8, utf-8;q=0.5, *;q=0.5',
  'HTTP_ACCEPT_LANGUAGE' => 'en',
  'HTTP_HOST' => 'webdav',
  'HTTP_CONNECTION' => 'Keep-Alive',
  'HTTP_DEPTH' => '0',
  'CONTENT_TYPE' => 'text/xml; charset=utf-8',
  'HTTP_CONTENT_LENGTH' => '303',
  'ORIG_SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php/',
  'ORIG_PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs//',
  'PHP_SELF' => '/index.php/',
  'REQUEST_TIME' => 1215594603,
);

?>