<?php

interface ezcDocumentOdtStylePropertyGenerator
{
    /**
     * Creates the style property from the attributes in $style.
     *
     * Creates the property generated by the specific style generator and 
     * renders all suitable styling attributes in $style into this property.
     * 
     * @param DOMElement $parent 
     * @param array $styles 
     */
    function createProperty( DOMElement $parent, array $styles );
}

?>
