<?php
// Autogenerated PersistentObject definition

$def = new ezcPersistentObjectDefinition();
$def->table = 'nested_set';
$def->class = 'nested_set';

$def->idProperty               = new ezcPersistentObjectIdProperty();
$def->idProperty->columnName   = 'id';
$def->idProperty->propertyName = 'id';
$def->idProperty->generator    = new ezcPersistentGeneratorDefinition( 'ezcPersistentManualGenerator' );


$def->properties['lft']               = new ezcPersistentObjectProperty();
$def->properties['lft']->columnName   = 'lft';
$def->properties['lft']->propertyName = 'lft';
$def->properties['lft']->propertyType = ezcPersistentObjectProperty::PHP_TYPE_INT;


$def->properties['parent_id']               = new ezcPersistentObjectProperty();
$def->properties['parent_id']->columnName   = 'parent_id';
$def->properties['parent_id']->propertyName = 'parent_id';
$def->properties['parent_id']->propertyType = ezcPersistentObjectProperty::PHP_TYPE_STRING;


$def->properties['rgt']               = new ezcPersistentObjectProperty();
$def->properties['rgt']->columnName   = 'rgt';
$def->properties['rgt']->propertyName = 'rgt';
$def->properties['rgt']->propertyType = ezcPersistentObjectProperty::PHP_TYPE_INT;

return $def;

?>
