ezcMvcRequest::__set_state(array(
   'date' => 
  DateTime::__set_state(array(
     'date' => '2008-07-18 09:49:08',
     'timezone_type' => 1,
     'timezone' => '+00:00',
  )),
   'protocol' => 'http-post',
   'host' => 'kossu',
   'uri' => '/test/test.php',
   'requestId' => 'kossu/test/test.php',
   'referrer' => 'http://kossu/test/upload.html',
   'variables' => 
  array (
  ),
   'body' => '',
   'files' => 
  array (
    0 => 
    ezcMvcRequestFile::__set_state(array(
       'mimeType' => 'image/jpeg',
       'name' => 'me_crop.jpg',
       'size' => 58050,
       'status' => 0,
       'tmpPath' => '/tmp/php7kglKS',
    )),
  ),
   'accept' => 
  ezcMvcRequestAccept::__set_state(array(
     'types' => 
    array (
      0 => 'text/html',
      1 => 'application/xhtml+xml',
      2 => 'application/xml',
      3 => '*/*',
    ),
     'charsets' => 
    array (
      0 => 'UTF-8',
      1 => '*',
    ),
     'languages' => 
    array (
      0 => 'en',
      1 => 'en-us',
      2 => 'nb',
      3 => 'nl',
    ),
     'encodings' => 
    array (
      0 => 'gzip',
      1 => 'deflate',
    ),
  )),
   'agent' => 
  ezcMvcRequestUserAgent::__set_state(array(
     'agent' => 'Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.0.1) Gecko/2008071420 Iceweasel/3.0.1 (Debian-3.0.1-1)',
  )),
   'authentication' => NULL,
   'raw' => 
  array (
    'CONTENT_LENGTH' => '58397',
    'CONTENT_TYPE' => 'multipart/form-data; boundary=---------------------------10609725428873912581030075601',
    'DOCUMENT_ROOT' => '/home/httpd/html',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'HTTP_ACCEPT_CHARSET' => 'UTF-8,*',
    'HTTP_ACCEPT_ENCODING' => 'gzip,deflate',
    'HTTP_ACCEPT_LANGUAGE' => 'en,en-us;q=0.8,nb;q=0.5,nl;q=0.3',
    'HTTP_CONNECTION' => 'keep-alive',
    'HTTP_HOST' => 'kossu',
    'HTTP_KEEP_ALIVE' => '3000',
    'HTTP_REFERER' => 'http://kossu/test/upload.html',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.0.1) Gecko/2008071420 Iceweasel/3.0.1 (Debian-3.0.1-1)',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'REMOTE_ADDR' => '127.0.1.1',
    'REMOTE_PORT' => '54346',
    'SCRIPT_FILENAME' => '/home/httpd/html/test/test.php',
    'SERVER_ADDR' => '127.0.1.1',
    'SERVER_ADMIN' => '[no address given]',
    'SERVER_NAME' => 'kossu',
    'SERVER_PORT' => '80',
    'SERVER_SIGNATURE' => '',
    'SERVER_SOFTWARE' => 'Apache/1.3.31 (Unix) PHP/5.3.0-dev',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'REQUEST_METHOD' => 'POST',
    'QUERY_STRING' => '',
    'REQUEST_URI' => '/test/test.php',
    'SCRIPT_NAME' => '/test/test.php',
    'PATH_TRANSLATED' => '/home/httpd/html/test/test.php',
    'PHP_SELF' => '/test/test.php',
    'REQUEST_TIME' => 1216374548,
    'argv' => 
    array (
    ),
    'argc' => 0,
  ),
   'cookies' => 
  array (
  ),
   'isFatal' => NULL,
))