ezcMvcRequest::__set_state(array(
   'date' => 
  DateTime::__set_state(array(
     'date' => '2008-07-18 09:51:35',
     'timezone_type' => 1,
     'timezone' => '+00:00',
  )),
   'protocol' => 'http-put',
   'host' => 'kossu',
   'uri' => '/test/test.php',
   'requestId' => 'kossu/test/test.php',
   'referrer' => NULL,
   'variables' => 
  array (
  ),
   'body' => '',
   'files' => NULL,
   'accept' => 
  ezcMvcRequestAccept::__set_state(array(
     'types' => 
    array (
      0 => '*/*',
    ),
     'charsets' => 
    array (
    ),
     'languages' => 
    array (
    ),
     'encodings' => 
    array (
    ),
  )),
   'agent' => 
  ezcMvcRequestUserAgent::__set_state(array(
     'agent' => 'curl/7.18.2 (x86_64-pc-linux-gnu) libcurl/7.18.2 OpenSSL/0.9.8g zlib/1.2.3.3 libidn/1.9 libssh2/0.18',
  )),
   'authentication' => NULL,
   'raw' => 
  array (
    'CONTENT_LENGTH' => '1878',
    'DOCUMENT_ROOT' => '/home/httpd/html',
    'HTTP_ACCEPT' => '*/*',
    'HTTP_EXPECT' => '100-continue',
    'HTTP_HOST' => 'kossu',
    'HTTP_USER_AGENT' => 'curl/7.18.2 (x86_64-pc-linux-gnu) libcurl/7.18.2 OpenSSL/0.9.8g zlib/1.2.3.3 libidn/1.9 libssh2/0.18',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'REMOTE_ADDR' => '127.0.1.1',
    'REMOTE_PORT' => '54356',
    'SCRIPT_FILENAME' => '/home/httpd/html/test/test.php',
    'SERVER_ADDR' => '127.0.1.1',
    'SERVER_ADMIN' => '[no address given]',
    'SERVER_NAME' => 'kossu',
    'SERVER_PORT' => '80',
    'SERVER_SIGNATURE' => '',
    'SERVER_SOFTWARE' => 'Apache/1.3.31 (Unix) PHP/5.3.0-dev',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'REQUEST_METHOD' => 'PUT',
    'QUERY_STRING' => '',
    'REQUEST_URI' => '/test/test.php',
    'SCRIPT_NAME' => '/test/test.php',
    'PATH_TRANSLATED' => '/home/httpd/html/test/test.php',
    'PHP_SELF' => '/test/test.php',
    'REQUEST_TIME' => 1216374695,
    'argv' => 
    array (
    ),
    'argc' => 0,
  ),
   'cookies' => 
  array (
  ),
   'isFatal' => NULL,
))