<?php
/**
 * Interface for all mock objects which are generated by ezcMock.
 */
interface ezcMockObject extends ezcMockVerifiable
{
    /**
     * Returns the current invocation mocker which keeps track of expecations
     * and stubs.
     * @return ezcMockInvocationMocker
     */
    public function getInvocationMocker();

    /**
     * Registers a new expectation in the mock object and returns the match
     * object which can be infused with further details.
     *
     * @param ezcMockInvocation $invocation The invocation handler for the method calls.
     * @return ezcMockMethodNameMatchBuilder
     */
    public function expects( ezcMockInvocationMatcher $invocation );

}
?>
