<?php

return array (
  'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/i686-pc-linux-gnu/gcc-bin/4.1.1:/usr/i686-pc-linux-gnu/gcc-bin/4.1.2:/opt/sun-jdk-1.4.2.14/bin:/opt/sun-jdk-1.4.2.14/jre/bin:/opt/sun-jdk-1.4.2.14/jre/javaws:/usr/kde/3.5/sbin:/usr/kde/3.5/bin:/usr/qt/3/bin:/opt/vmware/server/bin',
  'PWD' => '/var/www/webdav/bin',
  'PHP_FCGI_MAX_REQUESTS' => '10000',
  '_' => '/usr/local/php/php-5.2-cvs/bin/php-cgi',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.18',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '54919',
  'REMOTE_ADDR' => '127.0.0.1',
  'SCRIPT_NAME' => '/index.php',
  'SCRIPT_FILENAME' => '/var/www/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/var/www/webdav/htdocs/',
  'REQUEST_URI' => '/collection/subdir/new_collection/collection/put_test.zip',
  'REDIRECT_URI' => 'index.php',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'COPY',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.7 (like Gecko)',
  'HTTP_PRAGMA' => 'no-cache',
  'HTTP_CACHE_CONTROL' => 'no-cache',
  'HTTP_ACCEPT' => 'text/html, image/jpeg, image/png, text/*, image/*, */*',
  'HTTP_ACCEPT_ENCODING' => 'x-gzip, x-deflate, gzip, deflate',
  'HTTP_ACCEPT_CHARSET' => 'utf-8, utf-8;q=0.5, *;q=0.5',
  'HTTP_ACCEPT_LANGUAGE' => 'en',
  'HTTP_HOST' => 'webdav',
  'HTTP_CONNECTION' => 'Keep-Alive',
  'HTTP_DESTINATION' => 'http://webdav/collection/new_collection/collection/put_test.zip',
  'HTTP_DEPTH' => 'infinity',
  'HTTP_OVERWRITE' => 'F',
  'ORIG_PATH_INFO' => '',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME' => 1192632225,
);

?>