<?php

return array (
  'PWD' => '/',
  'LANG' => 'en_US.UTF-8',
  'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/opt/sun-jdk-1.4.2.17/bin:/opt/sun-jdk-1.4.2.17/jre/bin:/opt/sun-jdk-1.4.2.17/jre/javaws:/usr/kde/3.5/sbin:/usr/kde/3.5/bin:/usr/qt/3/bin:/usr/lib/subversion/bin',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '54393',
  'REMOTE_ADDR' => '127.0.0.1',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/some folder with spaces/put_test_utf8_filename_ςңα⊁∭⋉€₱‱⁌.txt',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/some folder with spaces/put_test_utf8_filename_ςңα⊁∭⋉€₱‱⁌.txt',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/some%20folder%20with%20spaces/put_test_utf8_filename_%CF%82%D2%A3%CE%B1%E2%8A%81%E2%88%AD%E2%8B%89%E2%82%AC%E2%82%B1%E2%80%B1%E2%81%8C.txt',
  'REDIRECT_URI' => '/index.php/some%20folder%20with%20spaces/put_test_utf8_filename_%CF%82%D2%A3%CE%B1%E2%8A%81%E2%88%AD%E2%8B%89%E2%82%AC%E2%82%B1%E2%80%B1%E2%81%8C.txt',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'GET',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.9 (like Gecko) (Gentoo)',
  'HTTP_ACCEPT' => 'text/html, image/jpeg, image/png, text/*, image/*, */*',
  'HTTP_ACCEPT_CHARSET' => 'utf-8, utf-8;q=0.5, *;q=0.5',
  'HTTP_ACCEPT_LANGUAGE' => 'en',
  'HTTP_HOST' => 'webdav',
  'HTTP_CONNECTION' => 'Keep-Alive',
  'ORIG_SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php/some folder with spaces/put_test_utf8_filename_ςңα⊁∭⋉€₱‱⁌.txt',
  'ORIG_PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs//some folder with spaces/put_test_utf8_filename_ςңα⊁∭⋉€₱‱⁌.txt',
  'PHP_SELF' => '/index.php/some folder with spaces/put_test_utf8_filename_ςңα⊁∭⋉€₱‱⁌.txt',
  'REQUEST_TIME' => 1215594679,
);

?>