<?php
/**
 * File containing the ezcDebugPhpStacktraceIterator class.
 *
 * @package Debug
 * @version //autogentag//
 * @copyright Copyright (C) 2005-2008 eZ systems as. All rights reserved.
 * @license http://ez.no/licenses/new_bsd New BSD License
 */

/**
 * Iterator class to wrap around debug_backtrace() stack traces.
 *
 * This iterator class receives a stack trace generated by debug_backtrace()
 * and unifies it as described in the {@link ezcDebugStacktraceIterator}
 * interface.
 * 
 * @package Debug
 * @version //autogen//
 * @copyright Copyright (C) 2005-2007 eZ systems as. All rights reserved.
 * @license http://ez.no/licenses/new_bsd New BSD License
 */
class ezcDebugPhpStacktraceIterator
{
    protected function prepare( $stackTrace )
    {
        return parent::prepare(
            // Pop first 2 elements to ignore log() and getStackTrace() calls
            array_slice( $stackTrace, 2 )
        );
    }

    /**
     * Unifies a stack element for being returned to the formatter.
     *
     * This method ensures that an element of the stack trace conforms to the
     * format expected by a {@link ezcDebugOutputFormatter}. The format is
     * defined as follows:
     *
     * <code>
     * array(
     *      'file'      => '<fullpathtofile>',
     *      'line'      => <lineno>,
     *      'function'  => '<functionname>',
     *      'class'     => '<classname>',
     *      'params'    => array(
     *          <param_no> => '<paramvalueinfo>',
     *          <param_no> => '<paramvalueinfo>',
     *          <param_no> => '<paramvalueinfo>',
     *          ...
     *      )
     * )
     * </code>
     * 
     * @param mixed $stackElement 
     * @return array As described above.
     */
    protected function unifyStackElement( $stackElement )
    {
        // Not to be set in the unified version
        unset( $stackElement['type'] );

        // Unify args -> params
        $stackElement['params'] = self::dumpVariables( $stackElement['args'] );
        unset( $stackElement['args'] );
        
        return $stackElement;
    }

    /**
     * Returns the arguments of a stack element as string dumps.
     *
     * Returns an array corresponding to the 'params' key of a unified stack
     * element, created from the 'args' ($args) element from an unified one.
     * 
     * @param array $args 
     * @return array
     */
    private function convertArgsToParams( $args )
    {
        $params = array();
        foreach ( $args as $arg )
        {
            $params[] = ezcDebugVariableDumpTool::dumpVariable( $arg );
        }
        return $params;
    }
}

?>
