<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.22',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/secure_collection/subdir/file.html',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/secure_collection/subdir/file.html',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/secure_collection/subdir/file.html',
  'REDIRECT_URI' => '/index.php/secure_collection/subdir/file.html',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'GET',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_CONNECTION' => 'Keep-Alive',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (compatible; Konqueror/4.2; Linux) KHTML/4.2.3 (like Gecko)',
  'HTTP_ACCEPT' => 'text/html, image/jpeg;q=0.9, image/png;q=0.9, text/*;q=0.9, image/*;q=0.9, */*;q=0.8',
  'HTTP_ACCEPT_CHARSET' => 'utf-8, utf-8;q=0.5, *;q=0.5',
  'HTTP_ACCEPT_LANGUAGE' => 'en-US, en',
  'HTTP_AUTHORIZATION' => 'Digest username="some", realm="eZ Components WebDAV", nonce="de35bbf9b97810e9b204ad3a2366c37f", uri="/secure_collection/subdir/file.html", algorithm="MD5", response="63c53c13ef92ae4eec64e2e861d70d0e"',
  'PHP_SELF' => '/index.php/secure_collection/subdir/file.html',
  'PHP_AUTH_DIGEST' => 'username="some", realm="eZ Components WebDAV", nonce="de35bbf9b97810e9b204ad3a2366c37f", uri="/secure_collection/subdir/file.html", algorithm="MD5", response="63c53c13ef92ae4eec64e2e861d70d0e"',
  'REQUEST_TIME' => 1220431173,
);

?>