<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.22',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'CONTENT_LENGTH' => '14013',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/secure_collection/subdir/collection/put_test.xml',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/secure_collection/subdir/collection/put_test.xml',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/secure_collection/subdir/collection/put_test.xml',
  'REDIRECT_URI' => '/index.php/secure_collection/subdir/collection/put_test.xml',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PUT',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_CONNECTION' => 'Keep-Alive',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (compatible; Konqueror/4.2; Linux) KHTML/4.2.3 (like Gecko)',
  'HTTP_PRAGMA' => 'no-cache',
  'HTTP_CACHE_CONTROL' => 'no-cache',
  'HTTP_ACCEPT' => 'text/html, image/jpeg;q=0.9, image/png;q=0.9, text/*;q=0.9, image/*;q=0.9, */*;q=0.8',
  'HTTP_ACCEPT_ENCODING' => 'x-gzip, x-deflate, gzip, deflate',
  'HTTP_ACCEPT_CHARSET' => 'utf-8, utf-8;q=0.5, *;q=0.5',
  'HTTP_ACCEPT_LANGUAGE' => 'en-US, en',
  'HTTP_AUTHORIZATION' => 'Digest username="some", realm="eZ Components WebDAV", nonce="fc30346a26203fb8be25475722288f59", uri="/secure_collection/subdir/collection/put_test.xml", algorithm="MD5", response="d4b70e5a76b4efcdd69f9a5691957905"',
  'HTTP_CONTENT_LENGTH' => '14013',
  'PHP_SELF' => '/index.php/secure_collection/subdir/collection/put_test.xml',
  'PHP_AUTH_DIGEST' => 'username="some", realm="eZ Components WebDAV", nonce="fc30346a26203fb8be25475722288f59", uri="/secure_collection/subdir/collection/put_test.xml", algorithm="MD5", response="d4b70e5a76b4efcdd69f9a5691957905"',
  'REQUEST_TIME' => 1220431173,
);

?>