<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'CONTENT_LENGTH' => '8',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/litmus/mkcolbody',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/litmus/mkcolbody',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/litmus/mkcolbody',
  'REDIRECT_URI' => '/index.php/litmus/mkcolbody',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'MKCOL',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'litmus/0.11 neon/0.26.3',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'CONTENT_TYPE' => 'xzy-foo/bar-512',
  'HTTP_CONTENT_LENGTH' => '8',
  'HTTP_X_LITMUS' => 'basic: 13 (mkcol_with_body)',
  'PHP_SELF' => '/index.php/litmus/mkcolbody',
  'REQUEST_TIME' => 1220431173,
);

?>