<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/litmus/ccdest2/',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/litmus/ccdest2/',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/litmus/ccdest2/',
  'REDIRECT_URI' => '/index.php/litmus/ccdest2/',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'COPY',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'litmus/0.11 neon/0.26.3',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_DEPTH' => 'infinity',
  'HTTP_DESTINATION' => 'http://webdav/litmus/ccdest/',
  'HTTP_OVERWRITE' => 'T',
  'HTTP_X_LITMUS' => 'copymove: 7 (copy_coll)',
  'PHP_SELF' => '/index.php/litmus/ccdest2/',
  'REQUEST_TIME' => 1220431173,
);

?>