<?php

return array (
  'LANG' => 'en_US.UTF-8',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33458',
  'REMOTE_ADDR' => '127.0.0.1',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/secure_collection/litmus/ccsrc/foo.9',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/secure_collection/litmus/ccsrc/foo.9',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/secure_collection/litmus/ccsrc/foo.9',
  'REDIRECT_URI' => '/index.php/secure_collection/litmus/ccsrc/foo.9',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PUT',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'litmus/0.11 neon/0.26.3',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_CONTENT_LENGTH' => '32',
  'HTTP_AUTHORIZATION' => 'Digest username="some", realm="eZ Components WebDAV", nonce="d744b7d75bc0c4f9772eb1b6e5490d09", uri="/secure_collection/litmus/ccsrc/foo.9", response="9f8ec303627c70b9c745d00f87b14730", algorithm="MD5"',
  'HTTP_X_LITMUS' => 'copymove: 7 (copy_coll)',
  'PHP_SELF' => '/index.php/secure_collection/litmus/ccsrc/foo.9',
  'PHP_AUTH_DIGEST' => 'username="some", realm="eZ Components WebDAV", nonce="d744b7d75bc0c4f9772eb1b6e5490d09", uri="/secure_collection/litmus/ccsrc/foo.9", response="9f8ec303627c70b9c745d00f87b14730", algorithm="MD5"',
  'REQUEST_TIME' => 1220431173,
);

?>