<?php

return array (
  'ORBIT_SOCKETDIR' => '/tmp/orbit-dotxp',
  'XERCESC_NLS_HOME' => '/usr/share/xerces-c/msg',
  'PWD' => '/',
  'LANG' => 'en_US.UTF-8',
  'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/opt/sun-jdk-1.4.2.18/bin:/opt/sun-jdk-1.4.2.18/jre/bin:/opt/sun-jdk-1.4.2.18/jre/javaws:/usr/kde/3.5/sbin:/usr/kde/3.5/bin:/usr/qt/3/bin:/usr/lib/subversion/bin',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.19',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '127.0.0.1',
  'REMOTE_PORT' => '33462',
  'REMOTE_ADDR' => '127.0.0.1',
  'CONTENT_LENGTH' => '32',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '/secure_collection/litmus/prop',
  'PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs/secure_collection/litmus/prop',
  'SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/home/dotxp/web/webdav/htdocs/',
  'REQUEST_URI' => '/secure_collection/litmus/prop',
  'REDIRECT_URI' => '/index.php/secure_collection/litmus/prop',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PUT',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_HOST' => 'webdav',
  'HTTP_USER_AGENT' => 'litmus/0.11 neon/0.26.3',
  'HTTP_CONNECTION' => 'TE',
  'HTTP_TE' => 'trailers',
  'HTTP_CONTENT_LENGTH' => '32',
  'HTTP_AUTHORIZATION' => 'Digest username="some", realm="eZ Components WebDAV", nonce="239e02626e6a1e2acc5d0e20c8465df5", uri="/secure_collection/litmus/prop", response="f26bd27acef7982653e3ebe3d6401e7a", algorithm="MD5"',
  'HTTP_X_LITMUS' => 'props: 5 (propinit)',
  'ORIG_SCRIPT_FILENAME' => '/home/dotxp/web/webdav/htdocs/index.php/secure_collection/litmus/prop',
  'ORIG_PATH_TRANSLATED' => '/home/dotxp/web/webdav/htdocs//secure_collection/litmus/prop',
  'PHP_SELF' => '/index.php/secure_collection/litmus/prop',
  'PHP_AUTH_DIGEST' => 'username="some", realm="eZ Components WebDAV", nonce="239e02626e6a1e2acc5d0e20c8465df5", uri="/secure_collection/litmus/prop", response="f26bd27acef7982653e3ebe3d6401e7a", algorithm="MD5"',
  'REQUEST_TIME' => 1219999598,
);

?>