<?php

return array (
  'PATH' => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/i686-pc-linux-gnu/gcc-bin/4.1.1:/usr/i686-pc-linux-gnu/gcc-bin/4.1.2:/opt/sun-jdk-1.4.2.14/bin:/opt/sun-jdk-1.4.2.14/jre/bin:/opt/sun-jdk-1.4.2.14/jre/javaws:/usr/kde/3.5/sbin:/usr/kde/3.5/bin:/usr/qt/3/bin:/opt/vmware/server/bin',
  'PWD' => '/var/www/webdav/bin',
  'PHP_FCGI_MAX_REQUESTS' => '10000',
  '_' => '/usr/local/php/php-5.2-stable/bin/php-cgi',
  'SERVER_SOFTWARE' => 'lighttpd/1.4.18',
  'SERVER_NAME' => 'webdav',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '192.168.1.46',
  'REMOTE_PORT' => '1051',
  'REMOTE_ADDR' => '192.168.1.21',
  'SCRIPT_NAME' => '/index.php',
  'PATH_INFO' => '',
  'SCRIPT_FILENAME' => '/var/www/webdav/htdocs/index.php',
  'DOCUMENT_ROOT' => '/var/www/webdav/htdocs/',
  'REQUEST_URI' => '/collection/Kopie%20von%20put_test/collection',
  'REDIRECT_URI' => 'index.php',
  'QUERY_STRING' => '',
  'REQUEST_METHOD' => 'PROPFIND',
  'REDIRECT_STATUS' => '200',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'HTTP_DEPTH' => '1',
  'HTTP_TRANSLATE' => 'f',
  'HTTP_USER_AGENT' => 'Microsoft-WebDAV-MiniRedir/5.1.2600',
  'HTTP_HOST' => 'webdav',
  'HTTP_CONTENT_LENGTH' => '0',
  'HTTP_CONNECTION' => 'Keep-Alive',
  'ORIG_PATH_INFO' => '',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME' => 1193309351,
);

?>