<?php
// Autogenerated class file

/**
 * Data class CamelCaseLetters.
 * Class to be used with eZ Components PersistentObject.
 */
class CamelCaseLetters
{
    /**
     * id
     *
     * @var int
     */
    private $id;
    /**
     * word
     *
     * @var string
     */
    private $word;

    /**
     * Set the PersistentObject state.
     *
     * @param array(string=>mixed) $state The state to set.
     * @return void
     */
     public function setState( array $state )
     {
         foreach ( $state as $attribute => $value )
         {
             $this->$attribute = $value;
         }
     }

    /**
     * Get the PersistentObject state.
     *
     * @return array(string=>mixed) The state of the object.
     */
     public function getState()
     {
         return array(
             'id' => $this->id,
             'word' => $this->word,
         );
     }
}
?>
