<?php
// Autogenerated class file

/**
 * Data class debugger.
 * Class to be used with eZ Components PersistentObject.
 */
class debugger
{
    /**
     * session_id
     *
     * @var string
     */
    private $session_id;

    /**
     * Set the PersistentObject state.
     *
     * @param array(string=>mixed) $state The state to set.
     * @return void
     */
     public function setState( array $state )
     {
         foreach ( $state as $attribute => $value )
         {
             $this->$attribute = $value;
         }
     }

    /**
     * Get the PersistentObject state.
     *
     * @return array(string=>mixed) The state of the object.
     */
     public function getState()
     {
         return array(
             'session_id' => $this->session_id,
         );
     }
}
?>
