<?php
// Autogenerated class file

/**
 * Data class liveuser_translations.
 * Class to be used with eZ Components PersistentObject.
 */
class liveuser_translations
{
    /**
     * description
     *
     * @var string
     */
    private $description;
    /**
     * language_id
     *
     * @var string
     */
    private $language_id;
    /**
     * name
     *
     * @var string
     */
    private $name;
    /**
     * section_id
     *
     * @var int
     */
    private $section_id;
    /**
     * section_type
     *
     * @var int
     */
    private $section_type;
    /**
     * translation_id
     *
     * @var int
     */
    private $translation_id;

    /**
     * Set the PersistentObject state.
     *
     * @param array(string=>mixed) $state The state to set.
     * @return void
     */
     public function setState( array $state )
     {
         foreach ( $state as $attribute => $value )
         {
             $this->$attribute = $value;
         }
     }

    /**
     * Get the PersistentObject state.
     *
     * @return array(string=>mixed) The state of the object.
     */
     public function getState()
     {
         return array(
             'description' => $this->description,
             'language_id' => $this->language_id,
             'name' => $this->name,
             'section_id' => $this->section_id,
             'section_type' => $this->section_type,
             'translation_id' => $this->translation_id,
         );
     }
}
?>
