<?php
/**
 * File containing a mapping from unicode lowercase to uppercase letters.
 *
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 * THIS FILE IS MACHINE GENERATED. USE THE FOLLOWING SCRIPT TO REBUILD IT:
 * - Template/src/unicode/generate_unicode_tables.php
 *
 * @package Template
 * @version //autogentag//
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @access private
 */

class ezcTemplateStringLowerToUpperUnicodeMap extends ezcBaseStruct
{
    public $unicodeTable = array(
    "\x61" => "\x41", // LATIN SMALL LETTER A
    "\x62" => "\x42", // LATIN SMALL LETTER B
    "\x63" => "\x43", // LATIN SMALL LETTER C
    "\x64" => "\x44", // LATIN SMALL LETTER D
    "\x65" => "\x45", // LATIN SMALL LETTER E
    "\x66" => "\x46", // LATIN SMALL LETTER F
    "\x67" => "\x47", // LATIN SMALL LETTER G
    "\x68" => "\x48", // LATIN SMALL LETTER H
    "\x69" => "\x49", // LATIN SMALL LETTER I
    "\x6a" => "\x4a", // LATIN SMALL LETTER J
    "\x6b" => "\x4b", // LATIN SMALL LETTER K
    "\x6c" => "\x4c", // LATIN SMALL LETTER L
    "\x6d" => "\x4d", // LATIN SMALL LETTER M
    "\x6e" => "\x4e", // LATIN SMALL LETTER N
    "\x6f" => "\x4f", // LATIN SMALL LETTER O
    "\x70" => "\x50", // LATIN SMALL LETTER P
    "\x71" => "\x51", // LATIN SMALL LETTER Q
    "\x72" => "\x52", // LATIN SMALL LETTER R
    "\x73" => "\x53", // LATIN SMALL LETTER S
    "\x74" => "\x54", // LATIN SMALL LETTER T
    "\x75" => "\x55", // LATIN SMALL LETTER U
    "\x76" => "\x56", // LATIN SMALL LETTER V
    "\x77" => "\x57", // LATIN SMALL LETTER W
    "\x78" => "\x58", // LATIN SMALL LETTER X
    "\x79" => "\x59", // LATIN SMALL LETTER Y
    "\x7a" => "\x5a", // LATIN SMALL LETTER Z
    "\xc2\xb5" => "\xce\x9c", // MICRO SIGN
    "\xc3\xa0" => "\xc3\x80", // LATIN SMALL LETTER A WITH GRAVE
    "\xc3\xa1" => "\xc3\x81", // LATIN SMALL LETTER A WITH ACUTE
    "\xc3\xa2" => "\xc3\x82", // LATIN SMALL LETTER A WITH CIRCUMFLEX
    "\xc3\xa3" => "\xc3\x83", // LATIN SMALL LETTER A WITH TILDE
    "\xc3\xa4" => "\xc3\x84", // LATIN SMALL LETTER A WITH DIAERESIS
    "\xc3\xa5" => "\xc3\x85", // LATIN SMALL LETTER A WITH RING ABOVE
    "\xc3\xa6" => "\xc3\x86", // LATIN SMALL LETTER AE
    "\xc3\xa7" => "\xc3\x87", // LATIN SMALL LETTER C WITH CEDILLA
    "\xc3\xa8" => "\xc3\x88", // LATIN SMALL LETTER E WITH GRAVE
    "\xc3\xa9" => "\xc3\x89", // LATIN SMALL LETTER E WITH ACUTE
    "\xc3\xaa" => "\xc3\x8a", // LATIN SMALL LETTER E WITH CIRCUMFLEX
    "\xc3\xab" => "\xc3\x8b", // LATIN SMALL LETTER E WITH DIAERESIS
    "\xc3\xac" => "\xc3\x8c", // LATIN SMALL LETTER I WITH GRAVE
    "\xc3\xad" => "\xc3\x8d", // LATIN SMALL LETTER I WITH ACUTE
    "\xc3\xae" => "\xc3\x8e", // LATIN SMALL LETTER I WITH CIRCUMFLEX
    "\xc3\xaf" => "\xc3\x8f", // LATIN SMALL LETTER I WITH DIAERESIS
    "\xc3\xb0" => "\xc3\x90", // LATIN SMALL LETTER ETH
    "\xc3\xb1" => "\xc3\x91", // LATIN SMALL LETTER N WITH TILDE
    "\xc3\xb2" => "\xc3\x92", // LATIN SMALL LETTER O WITH GRAVE
    "\xc3\xb3" => "\xc3\x93", // LATIN SMALL LETTER O WITH ACUTE
    "\xc3\xb4" => "\xc3\x94", // LATIN SMALL LETTER O WITH CIRCUMFLEX
    "\xc3\xb5" => "\xc3\x95", // LATIN SMALL LETTER O WITH TILDE
    "\xc3\xb6" => "\xc3\x96", // LATIN SMALL LETTER O WITH DIAERESIS
    "\xc3\xb8" => "\xc3\x98", // LATIN SMALL LETTER O WITH STROKE
    "\xc3\xb9" => "\xc3\x99", // LATIN SMALL LETTER U WITH GRAVE
    "\xc3\xba" => "\xc3\x9a", // LATIN SMALL LETTER U WITH ACUTE
    "\xc3\xbb" => "\xc3\x9b", // LATIN SMALL LETTER U WITH CIRCUMFLEX
    "\xc3\xbc" => "\xc3\x9c", // LATIN SMALL LETTER U WITH DIAERESIS
    "\xc3\xbd" => "\xc3\x9d", // LATIN SMALL LETTER Y WITH ACUTE
    "\xc3\xbe" => "\xc3\x9e", // LATIN SMALL LETTER THORN
    "\xc3\xbf" => "\xc5\xb8", // LATIN SMALL LETTER Y WITH DIAERESIS
    "\xc4\x81" => "\xc4\x80", // LATIN SMALL LETTER A WITH MACRON
    "\xc4\x83" => "\xc4\x82", // LATIN SMALL LETTER A WITH BREVE
    "\xc4\x85" => "\xc4\x84", // LATIN SMALL LETTER A WITH OGONEK
    "\xc4\x87" => "\xc4\x86", // LATIN SMALL LETTER C WITH ACUTE
    "\xc4\x89" => "\xc4\x88", // LATIN SMALL LETTER C WITH CIRCUMFLEX
    "\xc4\x8b" => "\xc4\x8a", // LATIN SMALL LETTER C WITH DOT ABOVE
    "\xc4\x8d" => "\xc4\x8c", // LATIN SMALL LETTER C WITH CARON
    "\xc4\x8f" => "\xc4\x8e", // LATIN SMALL LETTER D WITH CARON
    "\xc4\x91" => "\xc4\x90", // LATIN SMALL LETTER D WITH STROKE
    "\xc4\x93" => "\xc4\x92", // LATIN SMALL LETTER E WITH MACRON
    "\xc4\x95" => "\xc4\x94", // LATIN SMALL LETTER E WITH BREVE
    "\xc4\x97" => "\xc4\x96", // LATIN SMALL LETTER E WITH DOT ABOVE
    "\xc4\x99" => "\xc4\x98", // LATIN SMALL LETTER E WITH OGONEK
    "\xc4\x9b" => "\xc4\x9a", // LATIN SMALL LETTER E WITH CARON
    "\xc4\x9d" => "\xc4\x9c", // LATIN SMALL LETTER G WITH CIRCUMFLEX
    "\xc4\x9f" => "\xc4\x9e", // LATIN SMALL LETTER G WITH BREVE
    "\xc4\xa1" => "\xc4\xa0", // LATIN SMALL LETTER G WITH DOT ABOVE
    "\xc4\xa3" => "\xc4\xa2", // LATIN SMALL LETTER G WITH CEDILLA
    "\xc4\xa5" => "\xc4\xa4", // LATIN SMALL LETTER H WITH CIRCUMFLEX
    "\xc4\xa7" => "\xc4\xa6", // LATIN SMALL LETTER H WITH STROKE
    "\xc4\xa9" => "\xc4\xa8", // LATIN SMALL LETTER I WITH TILDE
    "\xc4\xab" => "\xc4\xaa", // LATIN SMALL LETTER I WITH MACRON
    "\xc4\xad" => "\xc4\xac", // LATIN SMALL LETTER I WITH BREVE
    "\xc4\xaf" => "\xc4\xae", // LATIN SMALL LETTER I WITH OGONEK
    "\xc4\xb1" => "\x49", // LATIN SMALL LETTER DOTLESS I
    "\xc4\xb3" => "\xc4\xb2", // LATIN SMALL LIGATURE IJ
    "\xc4\xb5" => "\xc4\xb4", // LATIN SMALL LETTER J WITH CIRCUMFLEX
    "\xc4\xb7" => "\xc4\xb6", // LATIN SMALL LETTER K WITH CEDILLA
    "\xc4\xba" => "\xc4\xb9", // LATIN SMALL LETTER L WITH ACUTE
    "\xc4\xbc" => "\xc4\xbb", // LATIN SMALL LETTER L WITH CEDILLA
    "\xc4\xbe" => "\xc4\xbd", // LATIN SMALL LETTER L WITH CARON
    "\xc5\x80" => "\xc4\xbf", // LATIN SMALL LETTER L WITH MIDDLE DOT
    "\xc5\x82" => "\xc5\x81", // LATIN SMALL LETTER L WITH STROKE
    "\xc5\x84" => "\xc5\x83", // LATIN SMALL LETTER N WITH ACUTE
    "\xc5\x86" => "\xc5\x85", // LATIN SMALL LETTER N WITH CEDILLA
    "\xc5\x88" => "\xc5\x87", // LATIN SMALL LETTER N WITH CARON
    "\xc5\x8b" => "\xc5\x8a", // LATIN SMALL LETTER ENG
    "\xc5\x8d" => "\xc5\x8c", // LATIN SMALL LETTER O WITH MACRON
    "\xc5\x8f" => "\xc5\x8e", // LATIN SMALL LETTER O WITH BREVE
    "\xc5\x91" => "\xc5\x90", // LATIN SMALL LETTER O WITH DOUBLE ACUTE
    "\xc5\x93" => "\xc5\x92", // LATIN SMALL LIGATURE OE
    "\xc5\x95" => "\xc5\x94", // LATIN SMALL LETTER R WITH ACUTE
    "\xc5\x97" => "\xc5\x96", // LATIN SMALL LETTER R WITH CEDILLA
    "\xc5\x99" => "\xc5\x98", // LATIN SMALL LETTER R WITH CARON
    "\xc5\x9b" => "\xc5\x9a", // LATIN SMALL LETTER S WITH ACUTE
    "\xc5\x9d" => "\xc5\x9c", // LATIN SMALL LETTER S WITH CIRCUMFLEX
    "\xc5\x9f" => "\xc5\x9e", // LATIN SMALL LETTER S WITH CEDILLA
    "\xc5\xa1" => "\xc5\xa0", // LATIN SMALL LETTER S WITH CARON
    "\xc5\xa3" => "\xc5\xa2", // LATIN SMALL LETTER T WITH CEDILLA
    "\xc5\xa5" => "\xc5\xa4", // LATIN SMALL LETTER T WITH CARON
    "\xc5\xa7" => "\xc5\xa6", // LATIN SMALL LETTER T WITH STROKE
    "\xc5\xa9" => "\xc5\xa8", // LATIN SMALL LETTER U WITH TILDE
    "\xc5\xab" => "\xc5\xaa", // LATIN SMALL LETTER U WITH MACRON
    "\xc5\xad" => "\xc5\xac", // LATIN SMALL LETTER U WITH BREVE
    "\xc5\xaf" => "\xc5\xae", // LATIN SMALL LETTER U WITH RING ABOVE
    "\xc5\xb1" => "\xc5\xb0", // LATIN SMALL LETTER U WITH DOUBLE ACUTE
    "\xc5\xb3" => "\xc5\xb2", // LATIN SMALL LETTER U WITH OGONEK
    "\xc5\xb5" => "\xc5\xb4", // LATIN SMALL LETTER W WITH CIRCUMFLEX
    "\xc5\xb7" => "\xc5\xb6", // LATIN SMALL LETTER Y WITH CIRCUMFLEX
    "\xc5\xba" => "\xc5\xb9", // LATIN SMALL LETTER Z WITH ACUTE
    "\xc5\xbc" => "\xc5\xbb", // LATIN SMALL LETTER Z WITH DOT ABOVE
    "\xc5\xbe" => "\xc5\xbd", // LATIN SMALL LETTER Z WITH CARON
    "\xc5\xbf" => "\x53", // LATIN SMALL LETTER LONG S
    "\xc6\x80" => "\xc9\x83", // LATIN SMALL LETTER B WITH STROKE
    "\xc6\x83" => "\xc6\x82", // LATIN SMALL LETTER B WITH TOPBAR
    "\xc6\x85" => "\xc6\x84", // LATIN SMALL LETTER TONE SIX
    "\xc6\x88" => "\xc6\x87", // LATIN SMALL LETTER C WITH HOOK
    "\xc6\x8c" => "\xc6\x8b", // LATIN SMALL LETTER D WITH TOPBAR
    "\xc6\x92" => "\xc6\x91", // LATIN SMALL LETTER F WITH HOOK
    "\xc6\x95" => "\xc7\xb6", // LATIN SMALL LETTER HV
    "\xc6\x99" => "\xc6\x98", // LATIN SMALL LETTER K WITH HOOK
    "\xc6\x9a" => "\xc8\xbd", // LATIN SMALL LETTER L WITH BAR
    "\xc6\x9e" => "\xc8\xa0", // LATIN SMALL LETTER N WITH LONG RIGHT LEG
    "\xc6\xa1" => "\xc6\xa0", // LATIN SMALL LETTER O WITH HORN
    "\xc6\xa3" => "\xc6\xa2", // LATIN SMALL LETTER OI
    "\xc6\xa5" => "\xc6\xa4", // LATIN SMALL LETTER P WITH HOOK
    "\xc6\xa8" => "\xc6\xa7", // LATIN SMALL LETTER TONE TWO
    "\xc6\xad" => "\xc6\xac", // LATIN SMALL LETTER T WITH HOOK
    "\xc6\xb0" => "\xc6\xaf", // LATIN SMALL LETTER U WITH HORN
    "\xc6\xb4" => "\xc6\xb3", // LATIN SMALL LETTER Y WITH HOOK
    "\xc6\xb6" => "\xc6\xb5", // LATIN SMALL LETTER Z WITH STROKE
    "\xc6\xb9" => "\xc6\xb8", // LATIN SMALL LETTER EZH REVERSED
    "\xc6\xbd" => "\xc6\xbc", // LATIN SMALL LETTER TONE FIVE
    "\xc6\xbf" => "\xc7\xb7", // LATIN LETTER WYNN
    "\xc7\x85" => "\xc7\x84", // LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON
    "\xc7\x86" => "\xc7\x84", // LATIN SMALL LETTER DZ WITH CARON
    "\xc7\x88" => "\xc7\x87", // LATIN CAPITAL LETTER L WITH SMALL LETTER J
    "\xc7\x89" => "\xc7\x87", // LATIN SMALL LETTER LJ
    "\xc7\x8b" => "\xc7\x8a", // LATIN CAPITAL LETTER N WITH SMALL LETTER J
    "\xc7\x8c" => "\xc7\x8a", // LATIN SMALL LETTER NJ
    "\xc7\x8e" => "\xc7\x8d", // LATIN SMALL LETTER A WITH CARON
    "\xc7\x90" => "\xc7\x8f", // LATIN SMALL LETTER I WITH CARON
    "\xc7\x92" => "\xc7\x91", // LATIN SMALL LETTER O WITH CARON
    "\xc7\x94" => "\xc7\x93", // LATIN SMALL LETTER U WITH CARON
    "\xc7\x96" => "\xc7\x95", // LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
    "\xc7\x98" => "\xc7\x97", // LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
    "\xc7\x9a" => "\xc7\x99", // LATIN SMALL LETTER U WITH DIAERESIS AND CARON
    "\xc7\x9c" => "\xc7\x9b", // LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
    "\xc7\x9d" => "\xc6\x8e", // LATIN SMALL LETTER TURNED E
    "\xc7\x9f" => "\xc7\x9e", // LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
    "\xc7\xa1" => "\xc7\xa0", // LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON
    "\xc7\xa3" => "\xc7\xa2", // LATIN SMALL LETTER AE WITH MACRON
    "\xc7\xa5" => "\xc7\xa4", // LATIN SMALL LETTER G WITH STROKE
    "\xc7\xa7" => "\xc7\xa6", // LATIN SMALL LETTER G WITH CARON
    "\xc7\xa9" => "\xc7\xa8", // LATIN SMALL LETTER K WITH CARON
    "\xc7\xab" => "\xc7\xaa", // LATIN SMALL LETTER O WITH OGONEK
    "\xc7\xad" => "\xc7\xac", // LATIN SMALL LETTER O WITH OGONEK AND MACRON
    "\xc7\xaf" => "\xc7\xae", // LATIN SMALL LETTER EZH WITH CARON
    "\xc7\xb2" => "\xc7\xb1", // LATIN CAPITAL LETTER D WITH SMALL LETTER Z
    "\xc7\xb3" => "\xc7\xb1", // LATIN SMALL LETTER DZ
    "\xc7\xb5" => "\xc7\xb4", // LATIN SMALL LETTER G WITH ACUTE
    "\xc7\xb9" => "\xc7\xb8", // LATIN SMALL LETTER N WITH GRAVE
    "\xc7\xbb" => "\xc7\xba", // LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
    "\xc7\xbd" => "\xc7\xbc", // LATIN SMALL LETTER AE WITH ACUTE
    "\xc7\xbf" => "\xc7\xbe", // LATIN SMALL LETTER O WITH STROKE AND ACUTE
    "\xc8\x81" => "\xc8\x80", // LATIN SMALL LETTER A WITH DOUBLE GRAVE
    "\xc8\x83" => "\xc8\x82", // LATIN SMALL LETTER A WITH INVERTED BREVE
    "\xc8\x85" => "\xc8\x84", // LATIN SMALL LETTER E WITH DOUBLE GRAVE
    "\xc8\x87" => "\xc8\x86", // LATIN SMALL LETTER E WITH INVERTED BREVE
    "\xc8\x89" => "\xc8\x88", // LATIN SMALL LETTER I WITH DOUBLE GRAVE
    "\xc8\x8b" => "\xc8\x8a", // LATIN SMALL LETTER I WITH INVERTED BREVE
    "\xc8\x8d" => "\xc8\x8c", // LATIN SMALL LETTER O WITH DOUBLE GRAVE
    "\xc8\x8f" => "\xc8\x8e", // LATIN SMALL LETTER O WITH INVERTED BREVE
    "\xc8\x91" => "\xc8\x90", // LATIN SMALL LETTER R WITH DOUBLE GRAVE
    "\xc8\x93" => "\xc8\x92", // LATIN SMALL LETTER R WITH INVERTED BREVE
    "\xc8\x95" => "\xc8\x94", // LATIN SMALL LETTER U WITH DOUBLE GRAVE
    "\xc8\x97" => "\xc8\x96", // LATIN SMALL LETTER U WITH INVERTED BREVE
    "\xc8\x99" => "\xc8\x98", // LATIN SMALL LETTER S WITH COMMA BELOW
    "\xc8\x9b" => "\xc8\x9a", // LATIN SMALL LETTER T WITH COMMA BELOW
    "\xc8\x9d" => "\xc8\x9c", // LATIN SMALL LETTER YOGH
    "\xc8\x9f" => "\xc8\x9e", // LATIN SMALL LETTER H WITH CARON
    "\xc8\xa3" => "\xc8\xa2", // LATIN SMALL LETTER OU
    "\xc8\xa5" => "\xc8\xa4", // LATIN SMALL LETTER Z WITH HOOK
    "\xc8\xa7" => "\xc8\xa6", // LATIN SMALL LETTER A WITH DOT ABOVE
    "\xc8\xa9" => "\xc8\xa8", // LATIN SMALL LETTER E WITH CEDILLA
    "\xc8\xab" => "\xc8\xaa", // LATIN SMALL LETTER O WITH DIAERESIS AND MACRON
    "\xc8\xad" => "\xc8\xac", // LATIN SMALL LETTER O WITH TILDE AND MACRON
    "\xc8\xaf" => "\xc8\xae", // LATIN SMALL LETTER O WITH DOT ABOVE
    "\xc8\xb1" => "\xc8\xb0", // LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON
    "\xc8\xb3" => "\xc8\xb2", // LATIN SMALL LETTER Y WITH MACRON
    "\xc8\xbc" => "\xc8\xbb", // LATIN SMALL LETTER C WITH STROKE
    "\xc8\xbf" => "\xe2\xb1\xbe", // LATIN SMALL LETTER S WITH SWASH TAIL
    "\xc9\x80" => "\xe2\xb1\xbf", // LATIN SMALL LETTER Z WITH SWASH TAIL
    "\xc9\x82" => "\xc9\x81", // LATIN SMALL LETTER GLOTTAL STOP
    "\xc9\x87" => "\xc9\x86", // LATIN SMALL LETTER E WITH STROKE
    "\xc9\x89" => "\xc9\x88", // LATIN SMALL LETTER J WITH STROKE
    "\xc9\x8b" => "\xc9\x8a", // LATIN SMALL LETTER Q WITH HOOK TAIL
    "\xc9\x8d" => "\xc9\x8c", // LATIN SMALL LETTER R WITH STROKE
    "\xc9\x8f" => "\xc9\x8e", // LATIN SMALL LETTER Y WITH STROKE
    "\xc9\x90" => "\xe2\xb1\xaf", // LATIN SMALL LETTER TURNED A
    "\xc9\x91" => "\xe2\xb1\xad", // LATIN SMALL LETTER ALPHA
    "\xc9\x92" => "\xe2\xb1\xb0", // LATIN SMALL LETTER TURNED ALPHA
    "\xc9\x93" => "\xc6\x81", // LATIN SMALL LETTER B WITH HOOK
    "\xc9\x94" => "\xc6\x86", // LATIN SMALL LETTER OPEN O
    "\xc9\x96" => "\xc6\x89", // LATIN SMALL LETTER D WITH TAIL
    "\xc9\x97" => "\xc6\x8a", // LATIN SMALL LETTER D WITH HOOK
    "\xc9\x99" => "\xc6\x8f", // LATIN SMALL LETTER SCHWA
    "\xc9\x9b" => "\xc6\x90", // LATIN SMALL LETTER OPEN E
    "\xc9\xa0" => "\xc6\x93", // LATIN SMALL LETTER G WITH HOOK
    "\xc9\xa3" => "\xc6\x94", // LATIN SMALL LETTER GAMMA
    "\xc9\xa5" => "\xea\x9e\x8d", // LATIN SMALL LETTER TURNED H
    "\xc9\xa8" => "\xc6\x97", // LATIN SMALL LETTER I WITH STROKE
    "\xc9\xa9" => "\xc6\x96", // LATIN SMALL LETTER IOTA
    "\xc9\xab" => "\xe2\xb1\xa2", // LATIN SMALL LETTER L WITH MIDDLE TILDE
    "\xc9\xaf" => "\xc6\x9c", // LATIN SMALL LETTER TURNED M
    "\xc9\xb1" => "\xe2\xb1\xae", // LATIN SMALL LETTER M WITH HOOK
    "\xc9\xb2" => "\xc6\x9d", // LATIN SMALL LETTER N WITH LEFT HOOK
    "\xc9\xb5" => "\xc6\x9f", // LATIN SMALL LETTER BARRED O
    "\xc9\xbd" => "\xe2\xb1\xa4", // LATIN SMALL LETTER R WITH TAIL
    "\xca\x80" => "\xc6\xa6", // LATIN LETTER SMALL CAPITAL R
    "\xca\x83" => "\xc6\xa9", // LATIN SMALL LETTER ESH
    "\xca\x88" => "\xc6\xae", // LATIN SMALL LETTER T WITH RETROFLEX HOOK
    "\xca\x89" => "\xc9\x84", // LATIN SMALL LETTER U BAR
    "\xca\x8a" => "\xc6\xb1", // LATIN SMALL LETTER UPSILON
    "\xca\x8b" => "\xc6\xb2", // LATIN SMALL LETTER V WITH HOOK
    "\xca\x8c" => "\xc9\x85", // LATIN SMALL LETTER TURNED V
    "\xca\x92" => "\xc6\xb7", // LATIN SMALL LETTER EZH
    "\xcd\x85" => "\xce\x99", // COMBINING GREEK YPOGEGRAMMENI
    "\xcd\xb1" => "\xcd\xb0", // GREEK SMALL LETTER HETA
    "\xcd\xb3" => "\xcd\xb2", // GREEK SMALL LETTER ARCHAIC SAMPI
    "\xcd\xb7" => "\xcd\xb6", // GREEK SMALL LETTER PAMPHYLIAN DIGAMMA
    "\xcd\xbb" => "\xcf\xbd", // GREEK SMALL REVERSED LUNATE SIGMA SYMBOL
    "\xcd\xbc" => "\xcf\xbe", // GREEK SMALL DOTTED LUNATE SIGMA SYMBOL
    "\xcd\xbd" => "\xcf\xbf", // GREEK SMALL REVERSED DOTTED LUNATE SIGMA SYMBOL
    "\xce\xac" => "\xce\x86", // GREEK SMALL LETTER ALPHA WITH TONOS
    "\xce\xad" => "\xce\x88", // GREEK SMALL LETTER EPSILON WITH TONOS
    "\xce\xae" => "\xce\x89", // GREEK SMALL LETTER ETA WITH TONOS
    "\xce\xaf" => "\xce\x8a", // GREEK SMALL LETTER IOTA WITH TONOS
    "\xce\xb1" => "\xce\x91", // GREEK SMALL LETTER ALPHA
    "\xce\xb2" => "\xce\x92", // GREEK SMALL LETTER BETA
    "\xce\xb3" => "\xce\x93", // GREEK SMALL LETTER GAMMA
    "\xce\xb4" => "\xce\x94", // GREEK SMALL LETTER DELTA
    "\xce\xb5" => "\xce\x95", // GREEK SMALL LETTER EPSILON
    "\xce\xb6" => "\xce\x96", // GREEK SMALL LETTER ZETA
    "\xce\xb7" => "\xce\x97", // GREEK SMALL LETTER ETA
    "\xce\xb8" => "\xce\x98", // GREEK SMALL LETTER THETA
    "\xce\xb9" => "\xce\x99", // GREEK SMALL LETTER IOTA
    "\xce\xba" => "\xce\x9a", // GREEK SMALL LETTER KAPPA
    "\xce\xbb" => "\xce\x9b", // GREEK SMALL LETTER LAMDA
    "\xce\xbc" => "\xce\x9c", // GREEK SMALL LETTER MU
    "\xce\xbd" => "\xce\x9d", // GREEK SMALL LETTER NU
    "\xce\xbe" => "\xce\x9e", // GREEK SMALL LETTER XI
    "\xce\xbf" => "\xce\x9f", // GREEK SMALL LETTER OMICRON
    "\xcf\x80" => "\xce\xa0", // GREEK SMALL LETTER PI
    "\xcf\x81" => "\xce\xa1", // GREEK SMALL LETTER RHO
    "\xcf\x82" => "\xce\xa3", // GREEK SMALL LETTER FINAL SIGMA
    "\xcf\x83" => "\xce\xa3", // GREEK SMALL LETTER SIGMA
    "\xcf\x84" => "\xce\xa4", // GREEK SMALL LETTER TAU
    "\xcf\x85" => "\xce\xa5", // GREEK SMALL LETTER UPSILON
    "\xcf\x86" => "\xce\xa6", // GREEK SMALL LETTER PHI
    "\xcf\x87" => "\xce\xa7", // GREEK SMALL LETTER CHI
    "\xcf\x88" => "\xce\xa8", // GREEK SMALL LETTER PSI
    "\xcf\x89" => "\xce\xa9", // GREEK SMALL LETTER OMEGA
    "\xcf\x8a" => "\xce\xaa", // GREEK SMALL LETTER IOTA WITH DIALYTIKA
    "\xcf\x8b" => "\xce\xab", // GREEK SMALL LETTER UPSILON WITH DIALYTIKA
    "\xcf\x8c" => "\xce\x8c", // GREEK SMALL LETTER OMICRON WITH TONOS
    "\xcf\x8d" => "\xce\x8e", // GREEK SMALL LETTER UPSILON WITH TONOS
    "\xcf\x8e" => "\xce\x8f", // GREEK SMALL LETTER OMEGA WITH TONOS
    "\xcf\x90" => "\xce\x92", // GREEK BETA SYMBOL
    "\xcf\x91" => "\xce\x98", // GREEK THETA SYMBOL
    "\xcf\x95" => "\xce\xa6", // GREEK PHI SYMBOL
    "\xcf\x96" => "\xce\xa0", // GREEK PI SYMBOL
    "\xcf\x97" => "\xcf\x8f", // GREEK KAI SYMBOL
    "\xcf\x99" => "\xcf\x98", // GREEK SMALL LETTER ARCHAIC KOPPA
    "\xcf\x9b" => "\xcf\x9a", // GREEK SMALL LETTER STIGMA
    "\xcf\x9d" => "\xcf\x9c", // GREEK SMALL LETTER DIGAMMA
    "\xcf\x9f" => "\xcf\x9e", // GREEK SMALL LETTER KOPPA
    "\xcf\xa1" => "\xcf\xa0", // GREEK SMALL LETTER SAMPI
    "\xcf\xa3" => "\xcf\xa2", // COPTIC SMALL LETTER SHEI
    "\xcf\xa5" => "\xcf\xa4", // COPTIC SMALL LETTER FEI
    "\xcf\xa7" => "\xcf\xa6", // COPTIC SMALL LETTER KHEI
    "\xcf\xa9" => "\xcf\xa8", // COPTIC SMALL LETTER HORI
    "\xcf\xab" => "\xcf\xaa", // COPTIC SMALL LETTER GANGIA
    "\xcf\xad" => "\xcf\xac", // COPTIC SMALL LETTER SHIMA
    "\xcf\xaf" => "\xcf\xae", // COPTIC SMALL LETTER DEI
    "\xcf\xb0" => "\xce\x9a", // GREEK KAPPA SYMBOL
    "\xcf\xb1" => "\xce\xa1", // GREEK RHO SYMBOL
    "\xcf\xb2" => "\xcf\xb9", // GREEK LUNATE SIGMA SYMBOL
    "\xcf\xb5" => "\xce\x95", // GREEK LUNATE EPSILON SYMBOL
    "\xcf\xb8" => "\xcf\xb7", // GREEK SMALL LETTER SHO
    "\xcf\xbb" => "\xcf\xba", // GREEK SMALL LETTER SAN
    "\xd0\xb0" => "\xd0\x90", // CYRILLIC SMALL LETTER A
    "\xd0\xb1" => "\xd0\x91", // CYRILLIC SMALL LETTER BE
    "\xd0\xb2" => "\xd0\x92", // CYRILLIC SMALL LETTER VE
    "\xd0\xb3" => "\xd0\x93", // CYRILLIC SMALL LETTER GHE
    "\xd0\xb4" => "\xd0\x94", // CYRILLIC SMALL LETTER DE
    "\xd0\xb5" => "\xd0\x95", // CYRILLIC SMALL LETTER IE
    "\xd0\xb6" => "\xd0\x96", // CYRILLIC SMALL LETTER ZHE
    "\xd0\xb7" => "\xd0\x97", // CYRILLIC SMALL LETTER ZE
    "\xd0\xb8" => "\xd0\x98", // CYRILLIC SMALL LETTER I
    "\xd0\xb9" => "\xd0\x99", // CYRILLIC SMALL LETTER SHORT I
    "\xd0\xba" => "\xd0\x9a", // CYRILLIC SMALL LETTER KA
    "\xd0\xbb" => "\xd0\x9b", // CYRILLIC SMALL LETTER EL
    "\xd0\xbc" => "\xd0\x9c", // CYRILLIC SMALL LETTER EM
    "\xd0\xbd" => "\xd0\x9d", // CYRILLIC SMALL LETTER EN
    "\xd0\xbe" => "\xd0\x9e", // CYRILLIC SMALL LETTER O
    "\xd0\xbf" => "\xd0\x9f", // CYRILLIC SMALL LETTER PE
    "\xd1\x80" => "\xd0\xa0", // CYRILLIC SMALL LETTER ER
    "\xd1\x81" => "\xd0\xa1", // CYRILLIC SMALL LETTER ES
    "\xd1\x82" => "\xd0\xa2", // CYRILLIC SMALL LETTER TE
    "\xd1\x83" => "\xd0\xa3", // CYRILLIC SMALL LETTER U
    "\xd1\x84" => "\xd0\xa4", // CYRILLIC SMALL LETTER EF
    "\xd1\x85" => "\xd0\xa5", // CYRILLIC SMALL LETTER HA
    "\xd1\x86" => "\xd0\xa6", // CYRILLIC SMALL LETTER TSE
    "\xd1\x87" => "\xd0\xa7", // CYRILLIC SMALL LETTER CHE
    "\xd1\x88" => "\xd0\xa8", // CYRILLIC SMALL LETTER SHA
    "\xd1\x89" => "\xd0\xa9", // CYRILLIC SMALL LETTER SHCHA
    "\xd1\x8a" => "\xd0\xaa", // CYRILLIC SMALL LETTER HARD SIGN
    "\xd1\x8b" => "\xd0\xab", // CYRILLIC SMALL LETTER YERU
    "\xd1\x8c" => "\xd0\xac", // CYRILLIC SMALL LETTER SOFT SIGN
    "\xd1\x8d" => "\xd0\xad", // CYRILLIC SMALL LETTER E
    "\xd1\x8e" => "\xd0\xae", // CYRILLIC SMALL LETTER YU
    "\xd1\x8f" => "\xd0\xaf", // CYRILLIC SMALL LETTER YA
    "\xd1\x90" => "\xd0\x80", // CYRILLIC SMALL LETTER IE WITH GRAVE
    "\xd1\x91" => "\xd0\x81", // CYRILLIC SMALL LETTER IO
    "\xd1\x92" => "\xd0\x82", // CYRILLIC SMALL LETTER DJE
    "\xd1\x93" => "\xd0\x83", // CYRILLIC SMALL LETTER GJE
    "\xd1\x94" => "\xd0\x84", // CYRILLIC SMALL LETTER UKRAINIAN IE
    "\xd1\x95" => "\xd0\x85", // CYRILLIC SMALL LETTER DZE
    "\xd1\x96" => "\xd0\x86", // CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
    "\xd1\x97" => "\xd0\x87", // CYRILLIC SMALL LETTER YI
    "\xd1\x98" => "\xd0\x88", // CYRILLIC SMALL LETTER JE
    "\xd1\x99" => "\xd0\x89", // CYRILLIC SMALL LETTER LJE
    "\xd1\x9a" => "\xd0\x8a", // CYRILLIC SMALL LETTER NJE
    "\xd1\x9b" => "\xd0\x8b", // CYRILLIC SMALL LETTER TSHE
    "\xd1\x9c" => "\xd0\x8c", // CYRILLIC SMALL LETTER KJE
    "\xd1\x9d" => "\xd0\x8d", // CYRILLIC SMALL LETTER I WITH GRAVE
    "\xd1\x9e" => "\xd0\x8e", // CYRILLIC SMALL LETTER SHORT U
    "\xd1\x9f" => "\xd0\x8f", // CYRILLIC SMALL LETTER DZHE
    "\xd1\xa1" => "\xd1\xa0", // CYRILLIC SMALL LETTER OMEGA
    "\xd1\xa3" => "\xd1\xa2", // CYRILLIC SMALL LETTER YAT
    "\xd1\xa5" => "\xd1\xa4", // CYRILLIC SMALL LETTER IOTIFIED E
    "\xd1\xa7" => "\xd1\xa6", // CYRILLIC SMALL LETTER LITTLE YUS
    "\xd1\xa9" => "\xd1\xa8", // CYRILLIC SMALL LETTER IOTIFIED LITTLE YUS
    "\xd1\xab" => "\xd1\xaa", // CYRILLIC SMALL LETTER BIG YUS
    "\xd1\xad" => "\xd1\xac", // CYRILLIC SMALL LETTER IOTIFIED BIG YUS
    "\xd1\xaf" => "\xd1\xae", // CYRILLIC SMALL LETTER KSI
    "\xd1\xb1" => "\xd1\xb0", // CYRILLIC SMALL LETTER PSI
    "\xd1\xb3" => "\xd1\xb2", // CYRILLIC SMALL LETTER FITA
    "\xd1\xb5" => "\xd1\xb4", // CYRILLIC SMALL LETTER IZHITSA
    "\xd1\xb7" => "\xd1\xb6", // CYRILLIC SMALL LETTER IZHITSA WITH DOUBLE GRAVE ACCENT
    "\xd1\xb9" => "\xd1\xb8", // CYRILLIC SMALL LETTER UK
    "\xd1\xbb" => "\xd1\xba", // CYRILLIC SMALL LETTER ROUND OMEGA
    "\xd1\xbd" => "\xd1\xbc", // CYRILLIC SMALL LETTER OMEGA WITH TITLO
    "\xd1\xbf" => "\xd1\xbe", // CYRILLIC SMALL LETTER OT
    "\xd2\x81" => "\xd2\x80", // CYRILLIC SMALL LETTER KOPPA
    "\xd2\x8b" => "\xd2\x8a", // CYRILLIC SMALL LETTER SHORT I WITH TAIL
    "\xd2\x8d" => "\xd2\x8c", // CYRILLIC SMALL LETTER SEMISOFT SIGN
    "\xd2\x8f" => "\xd2\x8e", // CYRILLIC SMALL LETTER ER WITH TICK
    "\xd2\x91" => "\xd2\x90", // CYRILLIC SMALL LETTER GHE WITH UPTURN
    "\xd2\x93" => "\xd2\x92", // CYRILLIC SMALL LETTER GHE WITH STROKE
    "\xd2\x95" => "\xd2\x94", // CYRILLIC SMALL LETTER GHE WITH MIDDLE HOOK
    "\xd2\x97" => "\xd2\x96", // CYRILLIC SMALL LETTER ZHE WITH DESCENDER
    "\xd2\x99" => "\xd2\x98", // CYRILLIC SMALL LETTER ZE WITH DESCENDER
    "\xd2\x9b" => "\xd2\x9a", // CYRILLIC SMALL LETTER KA WITH DESCENDER
    "\xd2\x9d" => "\xd2\x9c", // CYRILLIC SMALL LETTER KA WITH VERTICAL STROKE
    "\xd2\x9f" => "\xd2\x9e", // CYRILLIC SMALL LETTER KA WITH STROKE
    "\xd2\xa1" => "\xd2\xa0", // CYRILLIC SMALL LETTER BASHKIR KA
    "\xd2\xa3" => "\xd2\xa2", // CYRILLIC SMALL LETTER EN WITH DESCENDER
    "\xd2\xa5" => "\xd2\xa4", // CYRILLIC SMALL LIGATURE EN GHE
    "\xd2\xa7" => "\xd2\xa6", // CYRILLIC SMALL LETTER PE WITH MIDDLE HOOK
    "\xd2\xa9" => "\xd2\xa8", // CYRILLIC SMALL LETTER ABKHASIAN HA
    "\xd2\xab" => "\xd2\xaa", // CYRILLIC SMALL LETTER ES WITH DESCENDER
    "\xd2\xad" => "\xd2\xac", // CYRILLIC SMALL LETTER TE WITH DESCENDER
    "\xd2\xaf" => "\xd2\xae", // CYRILLIC SMALL LETTER STRAIGHT U
    "\xd2\xb1" => "\xd2\xb0", // CYRILLIC SMALL LETTER STRAIGHT U WITH STROKE
    "\xd2\xb3" => "\xd2\xb2", // CYRILLIC SMALL LETTER HA WITH DESCENDER
    "\xd2\xb5" => "\xd2\xb4", // CYRILLIC SMALL LIGATURE TE TSE
    "\xd2\xb7" => "\xd2\xb6", // CYRILLIC SMALL LETTER CHE WITH DESCENDER
    "\xd2\xb9" => "\xd2\xb8", // CYRILLIC SMALL LETTER CHE WITH VERTICAL STROKE
    "\xd2\xbb" => "\xd2\xba", // CYRILLIC SMALL LETTER SHHA
    "\xd2\xbd" => "\xd2\xbc", // CYRILLIC SMALL LETTER ABKHASIAN CHE
    "\xd2\xbf" => "\xd2\xbe", // CYRILLIC SMALL LETTER ABKHASIAN CHE WITH DESCENDER
    "\xd3\x82" => "\xd3\x81", // CYRILLIC SMALL LETTER ZHE WITH BREVE
    "\xd3\x84" => "\xd3\x83", // CYRILLIC SMALL LETTER KA WITH HOOK
    "\xd3\x86" => "\xd3\x85", // CYRILLIC SMALL LETTER EL WITH TAIL
    "\xd3\x88" => "\xd3\x87", // CYRILLIC SMALL LETTER EN WITH HOOK
    "\xd3\x8a" => "\xd3\x89", // CYRILLIC SMALL LETTER EN WITH TAIL
    "\xd3\x8c" => "\xd3\x8b", // CYRILLIC SMALL LETTER KHAKASSIAN CHE
    "\xd3\x8e" => "\xd3\x8d", // CYRILLIC SMALL LETTER EM WITH TAIL
    "\xd3\x8f" => "\xd3\x80", // CYRILLIC SMALL LETTER PALOCHKA
    "\xd3\x91" => "\xd3\x90", // CYRILLIC SMALL LETTER A WITH BREVE
    "\xd3\x93" => "\xd3\x92", // CYRILLIC SMALL LETTER A WITH DIAERESIS
    "\xd3\x95" => "\xd3\x94", // CYRILLIC SMALL LIGATURE A IE
    "\xd3\x97" => "\xd3\x96", // CYRILLIC SMALL LETTER IE WITH BREVE
    "\xd3\x99" => "\xd3\x98", // CYRILLIC SMALL LETTER SCHWA
    "\xd3\x9b" => "\xd3\x9a", // CYRILLIC SMALL LETTER SCHWA WITH DIAERESIS
    "\xd3\x9d" => "\xd3\x9c", // CYRILLIC SMALL LETTER ZHE WITH DIAERESIS
    "\xd3\x9f" => "\xd3\x9e", // CYRILLIC SMALL LETTER ZE WITH DIAERESIS
    "\xd3\xa1" => "\xd3\xa0", // CYRILLIC SMALL LETTER ABKHASIAN DZE
    "\xd3\xa3" => "\xd3\xa2", // CYRILLIC SMALL LETTER I WITH MACRON
    "\xd3\xa5" => "\xd3\xa4", // CYRILLIC SMALL LETTER I WITH DIAERESIS
    "\xd3\xa7" => "\xd3\xa6", // CYRILLIC SMALL LETTER O WITH DIAERESIS
    "\xd3\xa9" => "\xd3\xa8", // CYRILLIC SMALL LETTER BARRED O
    "\xd3\xab" => "\xd3\xaa", // CYRILLIC SMALL LETTER BARRED O WITH DIAERESIS
    "\xd3\xad" => "\xd3\xac", // CYRILLIC SMALL LETTER E WITH DIAERESIS
    "\xd3\xaf" => "\xd3\xae", // CYRILLIC SMALL LETTER U WITH MACRON
    "\xd3\xb1" => "\xd3\xb0", // CYRILLIC SMALL LETTER U WITH DIAERESIS
    "\xd3\xb3" => "\xd3\xb2", // CYRILLIC SMALL LETTER U WITH DOUBLE ACUTE
    "\xd3\xb5" => "\xd3\xb4", // CYRILLIC SMALL LETTER CHE WITH DIAERESIS
    "\xd3\xb7" => "\xd3\xb6", // CYRILLIC SMALL LETTER GHE WITH DESCENDER
    "\xd3\xb9" => "\xd3\xb8", // CYRILLIC SMALL LETTER YERU WITH DIAERESIS
    "\xd3\xbb" => "\xd3\xba", // CYRILLIC SMALL LETTER GHE WITH STROKE AND HOOK
    "\xd3\xbd" => "\xd3\xbc", // CYRILLIC SMALL LETTER HA WITH HOOK
    "\xd3\xbf" => "\xd3\xbe", // CYRILLIC SMALL LETTER HA WITH STROKE
    "\xd4\x81" => "\xd4\x80", // CYRILLIC SMALL LETTER KOMI DE
    "\xd4\x83" => "\xd4\x82", // CYRILLIC SMALL LETTER KOMI DJE
    "\xd4\x85" => "\xd4\x84", // CYRILLIC SMALL LETTER KOMI ZJE
    "\xd4\x87" => "\xd4\x86", // CYRILLIC SMALL LETTER KOMI DZJE
    "\xd4\x89" => "\xd4\x88", // CYRILLIC SMALL LETTER KOMI LJE
    "\xd4\x8b" => "\xd4\x8a", // CYRILLIC SMALL LETTER KOMI NJE
    "\xd4\x8d" => "\xd4\x8c", // CYRILLIC SMALL LETTER KOMI SJE
    "\xd4\x8f" => "\xd4\x8e", // CYRILLIC SMALL LETTER KOMI TJE
    "\xd4\x91" => "\xd4\x90", // CYRILLIC SMALL LETTER REVERSED ZE
    "\xd4\x93" => "\xd4\x92", // CYRILLIC SMALL LETTER EL WITH HOOK
    "\xd4\x95" => "\xd4\x94", // CYRILLIC SMALL LETTER LHA
    "\xd4\x97" => "\xd4\x96", // CYRILLIC SMALL LETTER RHA
    "\xd4\x99" => "\xd4\x98", // CYRILLIC SMALL LETTER YAE
    "\xd4\x9b" => "\xd4\x9a", // CYRILLIC SMALL LETTER QA
    "\xd4\x9d" => "\xd4\x9c", // CYRILLIC SMALL LETTER WE
    "\xd4\x9f" => "\xd4\x9e", // CYRILLIC SMALL LETTER ALEUT KA
    "\xd4\xa1" => "\xd4\xa0", // CYRILLIC SMALL LETTER EL WITH MIDDLE HOOK
    "\xd4\xa3" => "\xd4\xa2", // CYRILLIC SMALL LETTER EN WITH MIDDLE HOOK
    "\xd4\xa5" => "\xd4\xa4", // CYRILLIC SMALL LETTER PE WITH DESCENDER
    "\xd4\xa7" => "\xd4\xa6", // CYRILLIC SMALL LETTER SHHA WITH DESCENDER
    "\xd5\xa1" => "\xd4\xb1", // ARMENIAN SMALL LETTER AYB
    "\xd5\xa2" => "\xd4\xb2", // ARMENIAN SMALL LETTER BEN
    "\xd5\xa3" => "\xd4\xb3", // ARMENIAN SMALL LETTER GIM
    "\xd5\xa4" => "\xd4\xb4", // ARMENIAN SMALL LETTER DA
    "\xd5\xa5" => "\xd4\xb5", // ARMENIAN SMALL LETTER ECH
    "\xd5\xa6" => "\xd4\xb6", // ARMENIAN SMALL LETTER ZA
    "\xd5\xa7" => "\xd4\xb7", // ARMENIAN SMALL LETTER EH
    "\xd5\xa8" => "\xd4\xb8", // ARMENIAN SMALL LETTER ET
    "\xd5\xa9" => "\xd4\xb9", // ARMENIAN SMALL LETTER TO
    "\xd5\xaa" => "\xd4\xba", // ARMENIAN SMALL LETTER ZHE
    "\xd5\xab" => "\xd4\xbb", // ARMENIAN SMALL LETTER INI
    "\xd5\xac" => "\xd4\xbc", // ARMENIAN SMALL LETTER LIWN
    "\xd5\xad" => "\xd4\xbd", // ARMENIAN SMALL LETTER XEH
    "\xd5\xae" => "\xd4\xbe", // ARMENIAN SMALL LETTER CA
    "\xd5\xaf" => "\xd4\xbf", // ARMENIAN SMALL LETTER KEN
    "\xd5\xb0" => "\xd5\x80", // ARMENIAN SMALL LETTER HO
    "\xd5\xb1" => "\xd5\x81", // ARMENIAN SMALL LETTER JA
    "\xd5\xb2" => "\xd5\x82", // ARMENIAN SMALL LETTER GHAD
    "\xd5\xb3" => "\xd5\x83", // ARMENIAN SMALL LETTER CHEH
    "\xd5\xb4" => "\xd5\x84", // ARMENIAN SMALL LETTER MEN
    "\xd5\xb5" => "\xd5\x85", // ARMENIAN SMALL LETTER YI
    "\xd5\xb6" => "\xd5\x86", // ARMENIAN SMALL LETTER NOW
    "\xd5\xb7" => "\xd5\x87", // ARMENIAN SMALL LETTER SHA
    "\xd5\xb8" => "\xd5\x88", // ARMENIAN SMALL LETTER VO
    "\xd5\xb9" => "\xd5\x89", // ARMENIAN SMALL LETTER CHA
    "\xd5\xba" => "\xd5\x8a", // ARMENIAN SMALL LETTER PEH
    "\xd5\xbb" => "\xd5\x8b", // ARMENIAN SMALL LETTER JHEH
    "\xd5\xbc" => "\xd5\x8c", // ARMENIAN SMALL LETTER RA
    "\xd5\xbd" => "\xd5\x8d", // ARMENIAN SMALL LETTER SEH
    "\xd5\xbe" => "\xd5\x8e", // ARMENIAN SMALL LETTER VEW
    "\xd5\xbf" => "\xd5\x8f", // ARMENIAN SMALL LETTER TIWN
    "\xd6\x80" => "\xd5\x90", // ARMENIAN SMALL LETTER REH
    "\xd6\x81" => "\xd5\x91", // ARMENIAN SMALL LETTER CO
    "\xd6\x82" => "\xd5\x92", // ARMENIAN SMALL LETTER YIWN
    "\xd6\x83" => "\xd5\x93", // ARMENIAN SMALL LETTER PIWR
    "\xd6\x84" => "\xd5\x94", // ARMENIAN SMALL LETTER KEH
    "\xd6\x85" => "\xd5\x95", // ARMENIAN SMALL LETTER OH
    "\xd6\x86" => "\xd5\x96", // ARMENIAN SMALL LETTER FEH
    "\xe1\xb5\xb9" => "\xea\x9d\xbd", // LATIN SMALL LETTER INSULAR G
    "\xe1\xb5\xbd" => "\xe2\xb1\xa3", // LATIN SMALL LETTER P WITH STROKE
    "\xe1\xb8\x81" => "\xe1\xb8\x80", // LATIN SMALL LETTER A WITH RING BELOW
    "\xe1\xb8\x83" => "\xe1\xb8\x82", // LATIN SMALL LETTER B WITH DOT ABOVE
    "\xe1\xb8\x85" => "\xe1\xb8\x84", // LATIN SMALL LETTER B WITH DOT BELOW
    "\xe1\xb8\x87" => "\xe1\xb8\x86", // LATIN SMALL LETTER B WITH LINE BELOW
    "\xe1\xb8\x89" => "\xe1\xb8\x88", // LATIN SMALL LETTER C WITH CEDILLA AND ACUTE
    "\xe1\xb8\x8b" => "\xe1\xb8\x8a", // LATIN SMALL LETTER D WITH DOT ABOVE
    "\xe1\xb8\x8d" => "\xe1\xb8\x8c", // LATIN SMALL LETTER D WITH DOT BELOW
    "\xe1\xb8\x8f" => "\xe1\xb8\x8e", // LATIN SMALL LETTER D WITH LINE BELOW
    "\xe1\xb8\x91" => "\xe1\xb8\x90", // LATIN SMALL LETTER D WITH CEDILLA
    "\xe1\xb8\x93" => "\xe1\xb8\x92", // LATIN SMALL LETTER D WITH CIRCUMFLEX BELOW
    "\xe1\xb8\x95" => "\xe1\xb8\x94", // LATIN SMALL LETTER E WITH MACRON AND GRAVE
    "\xe1\xb8\x97" => "\xe1\xb8\x96", // LATIN SMALL LETTER E WITH MACRON AND ACUTE
    "\xe1\xb8\x99" => "\xe1\xb8\x98", // LATIN SMALL LETTER E WITH CIRCUMFLEX BELOW
    "\xe1\xb8\x9b" => "\xe1\xb8\x9a", // LATIN SMALL LETTER E WITH TILDE BELOW
    "\xe1\xb8\x9d" => "\xe1\xb8\x9c", // LATIN SMALL LETTER E WITH CEDILLA AND BREVE
    "\xe1\xb8\x9f" => "\xe1\xb8\x9e", // LATIN SMALL LETTER F WITH DOT ABOVE
    "\xe1\xb8\xa1" => "\xe1\xb8\xa0", // LATIN SMALL LETTER G WITH MACRON
    "\xe1\xb8\xa3" => "\xe1\xb8\xa2", // LATIN SMALL LETTER H WITH DOT ABOVE
    "\xe1\xb8\xa5" => "\xe1\xb8\xa4", // LATIN SMALL LETTER H WITH DOT BELOW
    "\xe1\xb8\xa7" => "\xe1\xb8\xa6", // LATIN SMALL LETTER H WITH DIAERESIS
    "\xe1\xb8\xa9" => "\xe1\xb8\xa8", // LATIN SMALL LETTER H WITH CEDILLA
    "\xe1\xb8\xab" => "\xe1\xb8\xaa", // LATIN SMALL LETTER H WITH BREVE BELOW
    "\xe1\xb8\xad" => "\xe1\xb8\xac", // LATIN SMALL LETTER I WITH TILDE BELOW
    "\xe1\xb8\xaf" => "\xe1\xb8\xae", // LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE
    "\xe1\xb8\xb1" => "\xe1\xb8\xb0", // LATIN SMALL LETTER K WITH ACUTE
    "\xe1\xb8\xb3" => "\xe1\xb8\xb2", // LATIN SMALL LETTER K WITH DOT BELOW
    "\xe1\xb8\xb5" => "\xe1\xb8\xb4", // LATIN SMALL LETTER K WITH LINE BELOW
    "\xe1\xb8\xb7" => "\xe1\xb8\xb6", // LATIN SMALL LETTER L WITH DOT BELOW
    "\xe1\xb8\xb9" => "\xe1\xb8\xb8", // LATIN SMALL LETTER L WITH DOT BELOW AND MACRON
    "\xe1\xb8\xbb" => "\xe1\xb8\xba", // LATIN SMALL LETTER L WITH LINE BELOW
    "\xe1\xb8\xbd" => "\xe1\xb8\xbc", // LATIN SMALL LETTER L WITH CIRCUMFLEX BELOW
    "\xe1\xb8\xbf" => "\xe1\xb8\xbe", // LATIN SMALL LETTER M WITH ACUTE
    "\xe1\xb9\x81" => "\xe1\xb9\x80", // LATIN SMALL LETTER M WITH DOT ABOVE
    "\xe1\xb9\x83" => "\xe1\xb9\x82", // LATIN SMALL LETTER M WITH DOT BELOW
    "\xe1\xb9\x85" => "\xe1\xb9\x84", // LATIN SMALL LETTER N WITH DOT ABOVE
    "\xe1\xb9\x87" => "\xe1\xb9\x86", // LATIN SMALL LETTER N WITH DOT BELOW
    "\xe1\xb9\x89" => "\xe1\xb9\x88", // LATIN SMALL LETTER N WITH LINE BELOW
    "\xe1\xb9\x8b" => "\xe1\xb9\x8a", // LATIN SMALL LETTER N WITH CIRCUMFLEX BELOW
    "\xe1\xb9\x8d" => "\xe1\xb9\x8c", // LATIN SMALL LETTER O WITH TILDE AND ACUTE
    "\xe1\xb9\x8f" => "\xe1\xb9\x8e", // LATIN SMALL LETTER O WITH TILDE AND DIAERESIS
    "\xe1\xb9\x91" => "\xe1\xb9\x90", // LATIN SMALL LETTER O WITH MACRON AND GRAVE
    "\xe1\xb9\x93" => "\xe1\xb9\x92", // LATIN SMALL LETTER O WITH MACRON AND ACUTE
    "\xe1\xb9\x95" => "\xe1\xb9\x94", // LATIN SMALL LETTER P WITH ACUTE
    "\xe1\xb9\x97" => "\xe1\xb9\x96", // LATIN SMALL LETTER P WITH DOT ABOVE
    "\xe1\xb9\x99" => "\xe1\xb9\x98", // LATIN SMALL LETTER R WITH DOT ABOVE
    "\xe1\xb9\x9b" => "\xe1\xb9\x9a", // LATIN SMALL LETTER R WITH DOT BELOW
    "\xe1\xb9\x9d" => "\xe1\xb9\x9c", // LATIN SMALL LETTER R WITH DOT BELOW AND MACRON
    "\xe1\xb9\x9f" => "\xe1\xb9\x9e", // LATIN SMALL LETTER R WITH LINE BELOW
    "\xe1\xb9\xa1" => "\xe1\xb9\xa0", // LATIN SMALL LETTER S WITH DOT ABOVE
    "\xe1\xb9\xa3" => "\xe1\xb9\xa2", // LATIN SMALL LETTER S WITH DOT BELOW
    "\xe1\xb9\xa5" => "\xe1\xb9\xa4", // LATIN SMALL LETTER S WITH ACUTE AND DOT ABOVE
    "\xe1\xb9\xa7" => "\xe1\xb9\xa6", // LATIN SMALL LETTER S WITH CARON AND DOT ABOVE
    "\xe1\xb9\xa9" => "\xe1\xb9\xa8", // LATIN SMALL LETTER S WITH DOT BELOW AND DOT ABOVE
    "\xe1\xb9\xab" => "\xe1\xb9\xaa", // LATIN SMALL LETTER T WITH DOT ABOVE
    "\xe1\xb9\xad" => "\xe1\xb9\xac", // LATIN SMALL LETTER T WITH DOT BELOW
    "\xe1\xb9\xaf" => "\xe1\xb9\xae", // LATIN SMALL LETTER T WITH LINE BELOW
    "\xe1\xb9\xb1" => "\xe1\xb9\xb0", // LATIN SMALL LETTER T WITH CIRCUMFLEX BELOW
    "\xe1\xb9\xb3" => "\xe1\xb9\xb2", // LATIN SMALL LETTER U WITH DIAERESIS BELOW
    "\xe1\xb9\xb5" => "\xe1\xb9\xb4", // LATIN SMALL LETTER U WITH TILDE BELOW
    "\xe1\xb9\xb7" => "\xe1\xb9\xb6", // LATIN SMALL LETTER U WITH CIRCUMFLEX BELOW
    "\xe1\xb9\xb9" => "\xe1\xb9\xb8", // LATIN SMALL LETTER U WITH TILDE AND ACUTE
    "\xe1\xb9\xbb" => "\xe1\xb9\xba", // LATIN SMALL LETTER U WITH MACRON AND DIAERESIS
    "\xe1\xb9\xbd" => "\xe1\xb9\xbc", // LATIN SMALL LETTER V WITH TILDE
    "\xe1\xb9\xbf" => "\xe1\xb9\xbe", // LATIN SMALL LETTER V WITH DOT BELOW
    "\xe1\xba\x81" => "\xe1\xba\x80", // LATIN SMALL LETTER W WITH GRAVE
    "\xe1\xba\x83" => "\xe1\xba\x82", // LATIN SMALL LETTER W WITH ACUTE
    "\xe1\xba\x85" => "\xe1\xba\x84", // LATIN SMALL LETTER W WITH DIAERESIS
    "\xe1\xba\x87" => "\xe1\xba\x86", // LATIN SMALL LETTER W WITH DOT ABOVE
    "\xe1\xba\x89" => "\xe1\xba\x88", // LATIN SMALL LETTER W WITH DOT BELOW
    "\xe1\xba\x8b" => "\xe1\xba\x8a", // LATIN SMALL LETTER X WITH DOT ABOVE
    "\xe1\xba\x8d" => "\xe1\xba\x8c", // LATIN SMALL LETTER X WITH DIAERESIS
    "\xe1\xba\x8f" => "\xe1\xba\x8e", // LATIN SMALL LETTER Y WITH DOT ABOVE
    "\xe1\xba\x91" => "\xe1\xba\x90", // LATIN SMALL LETTER Z WITH CIRCUMFLEX
    "\xe1\xba\x93" => "\xe1\xba\x92", // LATIN SMALL LETTER Z WITH DOT BELOW
    "\xe1\xba\x95" => "\xe1\xba\x94", // LATIN SMALL LETTER Z WITH LINE BELOW
    "\xe1\xba\x9b" => "\xe1\xb9\xa0", // LATIN SMALL LETTER LONG S WITH DOT ABOVE
    "\xe1\xba\xa1" => "\xe1\xba\xa0", // LATIN SMALL LETTER A WITH DOT BELOW
    "\xe1\xba\xa3" => "\xe1\xba\xa2", // LATIN SMALL LETTER A WITH HOOK ABOVE
    "\xe1\xba\xa5" => "\xe1\xba\xa4", // LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE
    "\xe1\xba\xa7" => "\xe1\xba\xa6", // LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE
    "\xe1\xba\xa9" => "\xe1\xba\xa8", // LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
    "\xe1\xba\xab" => "\xe1\xba\xaa", // LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE
    "\xe1\xba\xad" => "\xe1\xba\xac", // LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW
    "\xe1\xba\xaf" => "\xe1\xba\xae", // LATIN SMALL LETTER A WITH BREVE AND ACUTE
    "\xe1\xba\xb1" => "\xe1\xba\xb0", // LATIN SMALL LETTER A WITH BREVE AND GRAVE
    "\xe1\xba\xb3" => "\xe1\xba\xb2", // LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE
    "\xe1\xba\xb5" => "\xe1\xba\xb4", // LATIN SMALL LETTER A WITH BREVE AND TILDE
    "\xe1\xba\xb7" => "\xe1\xba\xb6", // LATIN SMALL LETTER A WITH BREVE AND DOT BELOW
    "\xe1\xba\xb9" => "\xe1\xba\xb8", // LATIN SMALL LETTER E WITH DOT BELOW
    "\xe1\xba\xbb" => "\xe1\xba\xba", // LATIN SMALL LETTER E WITH HOOK ABOVE
    "\xe1\xba\xbd" => "\xe1\xba\xbc", // LATIN SMALL LETTER E WITH TILDE
    "\xe1\xba\xbf" => "\xe1\xba\xbe", // LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE
    "\xe1\xbb\x81" => "\xe1\xbb\x80", // LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE
    "\xe1\xbb\x83" => "\xe1\xbb\x82", // LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
    "\xe1\xbb\x85" => "\xe1\xbb\x84", // LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE
    "\xe1\xbb\x87" => "\xe1\xbb\x86", // LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW
    "\xe1\xbb\x89" => "\xe1\xbb\x88", // LATIN SMALL LETTER I WITH HOOK ABOVE
    "\xe1\xbb\x8b" => "\xe1\xbb\x8a", // LATIN SMALL LETTER I WITH DOT BELOW
    "\xe1\xbb\x8d" => "\xe1\xbb\x8c", // LATIN SMALL LETTER O WITH DOT BELOW
    "\xe1\xbb\x8f" => "\xe1\xbb\x8e", // LATIN SMALL LETTER O WITH HOOK ABOVE
    "\xe1\xbb\x91" => "\xe1\xbb\x90", // LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE
    "\xe1\xbb\x93" => "\xe1\xbb\x92", // LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE
    "\xe1\xbb\x95" => "\xe1\xbb\x94", // LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
    "\xe1\xbb\x97" => "\xe1\xbb\x96", // LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE
    "\xe1\xbb\x99" => "\xe1\xbb\x98", // LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW
    "\xe1\xbb\x9b" => "\xe1\xbb\x9a", // LATIN SMALL LETTER O WITH HORN AND ACUTE
    "\xe1\xbb\x9d" => "\xe1\xbb\x9c", // LATIN SMALL LETTER O WITH HORN AND GRAVE
    "\xe1\xbb\x9f" => "\xe1\xbb\x9e", // LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE
    "\xe1\xbb\xa1" => "\xe1\xbb\xa0", // LATIN SMALL LETTER O WITH HORN AND TILDE
    "\xe1\xbb\xa3" => "\xe1\xbb\xa2", // LATIN SMALL LETTER O WITH HORN AND DOT BELOW
    "\xe1\xbb\xa5" => "\xe1\xbb\xa4", // LATIN SMALL LETTER U WITH DOT BELOW
    "\xe1\xbb\xa7" => "\xe1\xbb\xa6", // LATIN SMALL LETTER U WITH HOOK ABOVE
    "\xe1\xbb\xa9" => "\xe1\xbb\xa8", // LATIN SMALL LETTER U WITH HORN AND ACUTE
    "\xe1\xbb\xab" => "\xe1\xbb\xaa", // LATIN SMALL LETTER U WITH HORN AND GRAVE
    "\xe1\xbb\xad" => "\xe1\xbb\xac", // LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE
    "\xe1\xbb\xaf" => "\xe1\xbb\xae", // LATIN SMALL LETTER U WITH HORN AND TILDE
    "\xe1\xbb\xb1" => "\xe1\xbb\xb0", // LATIN SMALL LETTER U WITH HORN AND DOT BELOW
    "\xe1\xbb\xb3" => "\xe1\xbb\xb2", // LATIN SMALL LETTER Y WITH GRAVE
    "\xe1\xbb\xb5" => "\xe1\xbb\xb4", // LATIN SMALL LETTER Y WITH DOT BELOW
    "\xe1\xbb\xb7" => "\xe1\xbb\xb6", // LATIN SMALL LETTER Y WITH HOOK ABOVE
    "\xe1\xbb\xb9" => "\xe1\xbb\xb8", // LATIN SMALL LETTER Y WITH TILDE
    "\xe1\xbb\xbb" => "\xe1\xbb\xba", // LATIN SMALL LETTER MIDDLE-WELSH LL
    "\xe1\xbb\xbd" => "\xe1\xbb\xbc", // LATIN SMALL LETTER MIDDLE-WELSH V
    "\xe1\xbb\xbf" => "\xe1\xbb\xbe", // LATIN SMALL LETTER Y WITH LOOP
    "\xe1\xbc\x80" => "\xe1\xbc\x88", // GREEK SMALL LETTER ALPHA WITH PSILI
    "\xe1\xbc\x81" => "\xe1\xbc\x89", // GREEK SMALL LETTER ALPHA WITH DASIA
    "\xe1\xbc\x82" => "\xe1\xbc\x8a", // GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA
    "\xe1\xbc\x83" => "\xe1\xbc\x8b", // GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA
    "\xe1\xbc\x84" => "\xe1\xbc\x8c", // GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA
    "\xe1\xbc\x85" => "\xe1\xbc\x8d", // GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA
    "\xe1\xbc\x86" => "\xe1\xbc\x8e", // GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI
    "\xe1\xbc\x87" => "\xe1\xbc\x8f", // GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI
    "\xe1\xbc\x90" => "\xe1\xbc\x98", // GREEK SMALL LETTER EPSILON WITH PSILI
    "\xe1\xbc\x91" => "\xe1\xbc\x99", // GREEK SMALL LETTER EPSILON WITH DASIA
    "\xe1\xbc\x92" => "\xe1\xbc\x9a", // GREEK SMALL LETTER EPSILON WITH PSILI AND VARIA
    "\xe1\xbc\x93" => "\xe1\xbc\x9b", // GREEK SMALL LETTER EPSILON WITH DASIA AND VARIA
    "\xe1\xbc\x94" => "\xe1\xbc\x9c", // GREEK SMALL LETTER EPSILON WITH PSILI AND OXIA
    "\xe1\xbc\x95" => "\xe1\xbc\x9d", // GREEK SMALL LETTER EPSILON WITH DASIA AND OXIA
    "\xe1\xbc\xa0" => "\xe1\xbc\xa8", // GREEK SMALL LETTER ETA WITH PSILI
    "\xe1\xbc\xa1" => "\xe1\xbc\xa9", // GREEK SMALL LETTER ETA WITH DASIA
    "\xe1\xbc\xa2" => "\xe1\xbc\xaa", // GREEK SMALL LETTER ETA WITH PSILI AND VARIA
    "\xe1\xbc\xa3" => "\xe1\xbc\xab", // GREEK SMALL LETTER ETA WITH DASIA AND VARIA
    "\xe1\xbc\xa4" => "\xe1\xbc\xac", // GREEK SMALL LETTER ETA WITH PSILI AND OXIA
    "\xe1\xbc\xa5" => "\xe1\xbc\xad", // GREEK SMALL LETTER ETA WITH DASIA AND OXIA
    "\xe1\xbc\xa6" => "\xe1\xbc\xae", // GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI
    "\xe1\xbc\xa7" => "\xe1\xbc\xaf", // GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI
    "\xe1\xbc\xb0" => "\xe1\xbc\xb8", // GREEK SMALL LETTER IOTA WITH PSILI
    "\xe1\xbc\xb1" => "\xe1\xbc\xb9", // GREEK SMALL LETTER IOTA WITH DASIA
    "\xe1\xbc\xb2" => "\xe1\xbc\xba", // GREEK SMALL LETTER IOTA WITH PSILI AND VARIA
    "\xe1\xbc\xb3" => "\xe1\xbc\xbb", // GREEK SMALL LETTER IOTA WITH DASIA AND VARIA
    "\xe1\xbc\xb4" => "\xe1\xbc\xbc", // GREEK SMALL LETTER IOTA WITH PSILI AND OXIA
    "\xe1\xbc\xb5" => "\xe1\xbc\xbd", // GREEK SMALL LETTER IOTA WITH DASIA AND OXIA
    "\xe1\xbc\xb6" => "\xe1\xbc\xbe", // GREEK SMALL LETTER IOTA WITH PSILI AND PERISPOMENI
    "\xe1\xbc\xb7" => "\xe1\xbc\xbf", // GREEK SMALL LETTER IOTA WITH DASIA AND PERISPOMENI
    "\xe1\xbd\x80" => "\xe1\xbd\x88", // GREEK SMALL LETTER OMICRON WITH PSILI
    "\xe1\xbd\x81" => "\xe1\xbd\x89", // GREEK SMALL LETTER OMICRON WITH DASIA
    "\xe1\xbd\x82" => "\xe1\xbd\x8a", // GREEK SMALL LETTER OMICRON WITH PSILI AND VARIA
    "\xe1\xbd\x83" => "\xe1\xbd\x8b", // GREEK SMALL LETTER OMICRON WITH DASIA AND VARIA
    "\xe1\xbd\x84" => "\xe1\xbd\x8c", // GREEK SMALL LETTER OMICRON WITH PSILI AND OXIA
    "\xe1\xbd\x85" => "\xe1\xbd\x8d", // GREEK SMALL LETTER OMICRON WITH DASIA AND OXIA
    "\xe1\xbd\x91" => "\xe1\xbd\x99", // GREEK SMALL LETTER UPSILON WITH DASIA
    "\xe1\xbd\x93" => "\xe1\xbd\x9b", // GREEK SMALL LETTER UPSILON WITH DASIA AND VARIA
    "\xe1\xbd\x95" => "\xe1\xbd\x9d", // GREEK SMALL LETTER UPSILON WITH DASIA AND OXIA
    "\xe1\xbd\x97" => "\xe1\xbd\x9f", // GREEK SMALL LETTER UPSILON WITH DASIA AND PERISPOMENI
    "\xe1\xbd\xa0" => "\xe1\xbd\xa8", // GREEK SMALL LETTER OMEGA WITH PSILI
    "\xe1\xbd\xa1" => "\xe1\xbd\xa9", // GREEK SMALL LETTER OMEGA WITH DASIA
    "\xe1\xbd\xa2" => "\xe1\xbd\xaa", // GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA
    "\xe1\xbd\xa3" => "\xe1\xbd\xab", // GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA
    "\xe1\xbd\xa4" => "\xe1\xbd\xac", // GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA
    "\xe1\xbd\xa5" => "\xe1\xbd\xad", // GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA
    "\xe1\xbd\xa6" => "\xe1\xbd\xae", // GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI
    "\xe1\xbd\xa7" => "\xe1\xbd\xaf", // GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI
    "\xe1\xbd\xb0" => "\xe1\xbe\xba", // GREEK SMALL LETTER ALPHA WITH VARIA
    "\xe1\xbd\xb1" => "\xe1\xbe\xbb", // GREEK SMALL LETTER ALPHA WITH OXIA
    "\xe1\xbd\xb2" => "\xe1\xbf\x88", // GREEK SMALL LETTER EPSILON WITH VARIA
    "\xe1\xbd\xb3" => "\xe1\xbf\x89", // GREEK SMALL LETTER EPSILON WITH OXIA
    "\xe1\xbd\xb4" => "\xe1\xbf\x8a", // GREEK SMALL LETTER ETA WITH VARIA
    "\xe1\xbd\xb5" => "\xe1\xbf\x8b", // GREEK SMALL LETTER ETA WITH OXIA
    "\xe1\xbd\xb6" => "\xe1\xbf\x9a", // GREEK SMALL LETTER IOTA WITH VARIA
    "\xe1\xbd\xb7" => "\xe1\xbf\x9b", // GREEK SMALL LETTER IOTA WITH OXIA
    "\xe1\xbd\xb8" => "\xe1\xbf\xb8", // GREEK SMALL LETTER OMICRON WITH VARIA
    "\xe1\xbd\xb9" => "\xe1\xbf\xb9", // GREEK SMALL LETTER OMICRON WITH OXIA
    "\xe1\xbd\xba" => "\xe1\xbf\xaa", // GREEK SMALL LETTER UPSILON WITH VARIA
    "\xe1\xbd\xbb" => "\xe1\xbf\xab", // GREEK SMALL LETTER UPSILON WITH OXIA
    "\xe1\xbd\xbc" => "\xe1\xbf\xba", // GREEK SMALL LETTER OMEGA WITH VARIA
    "\xe1\xbd\xbd" => "\xe1\xbf\xbb", // GREEK SMALL LETTER OMEGA WITH OXIA
    "\xe1\xbe\x80" => "\xe1\xbe\x88", // GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI
    "\xe1\xbe\x81" => "\xe1\xbe\x89", // GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI
    "\xe1\xbe\x82" => "\xe1\xbe\x8a", // GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
    "\xe1\xbe\x83" => "\xe1\xbe\x8b", // GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
    "\xe1\xbe\x84" => "\xe1\xbe\x8c", // GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
    "\xe1\xbe\x85" => "\xe1\xbe\x8d", // GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
    "\xe1\xbe\x86" => "\xe1\xbe\x8e", // GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
    "\xe1\xbe\x87" => "\xe1\xbe\x8f", // GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
    "\xe1\xbe\x90" => "\xe1\xbe\x98", // GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI
    "\xe1\xbe\x91" => "\xe1\xbe\x99", // GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI
    "\xe1\xbe\x92" => "\xe1\xbe\x9a", // GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
    "\xe1\xbe\x93" => "\xe1\xbe\x9b", // GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
    "\xe1\xbe\x94" => "\xe1\xbe\x9c", // GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
    "\xe1\xbe\x95" => "\xe1\xbe\x9d", // GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
    "\xe1\xbe\x96" => "\xe1\xbe\x9e", // GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
    "\xe1\xbe\x97" => "\xe1\xbe\x9f", // GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
    "\xe1\xbe\xa0" => "\xe1\xbe\xa8", // GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI
    "\xe1\xbe\xa1" => "\xe1\xbe\xa9", // GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI
    "\xe1\xbe\xa2" => "\xe1\xbe\xaa", // GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
    "\xe1\xbe\xa3" => "\xe1\xbe\xab", // GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
    "\xe1\xbe\xa4" => "\xe1\xbe\xac", // GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
    "\xe1\xbe\xa5" => "\xe1\xbe\xad", // GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
    "\xe1\xbe\xa6" => "\xe1\xbe\xae", // GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
    "\xe1\xbe\xa7" => "\xe1\xbe\xaf", // GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
    "\xe1\xbe\xb0" => "\xe1\xbe\xb8", // GREEK SMALL LETTER ALPHA WITH VRACHY
    "\xe1\xbe\xb1" => "\xe1\xbe\xb9", // GREEK SMALL LETTER ALPHA WITH MACRON
    "\xe1\xbe\xb3" => "\xe1\xbe\xbc", // GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI
    "\xe1\xbe\xbe" => "\xce\x99", // GREEK PROSGEGRAMMENI
    "\xe1\xbf\x83" => "\xe1\xbf\x8c", // GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI
    "\xe1\xbf\x90" => "\xe1\xbf\x98", // GREEK SMALL LETTER IOTA WITH VRACHY
    "\xe1\xbf\x91" => "\xe1\xbf\x99", // GREEK SMALL LETTER IOTA WITH MACRON
    "\xe1\xbf\xa0" => "\xe1\xbf\xa8", // GREEK SMALL LETTER UPSILON WITH VRACHY
    "\xe1\xbf\xa1" => "\xe1\xbf\xa9", // GREEK SMALL LETTER UPSILON WITH MACRON
    "\xe1\xbf\xa5" => "\xe1\xbf\xac", // GREEK SMALL LETTER RHO WITH DASIA
    "\xe1\xbf\xb3" => "\xe1\xbf\xbc", // GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI
    "\xe2\x85\x8e" => "\xe2\x84\xb2", // TURNED SMALL F
    "\xe2\x85\xb0" => "\xe2\x85\xa0", // SMALL ROMAN NUMERAL ONE
    "\xe2\x85\xb1" => "\xe2\x85\xa1", // SMALL ROMAN NUMERAL TWO
    "\xe2\x85\xb2" => "\xe2\x85\xa2", // SMALL ROMAN NUMERAL THREE
    "\xe2\x85\xb3" => "\xe2\x85\xa3", // SMALL ROMAN NUMERAL FOUR
    "\xe2\x85\xb4" => "\xe2\x85\xa4", // SMALL ROMAN NUMERAL FIVE
    "\xe2\x85\xb5" => "\xe2\x85\xa5", // SMALL ROMAN NUMERAL SIX
    "\xe2\x85\xb6" => "\xe2\x85\xa6", // SMALL ROMAN NUMERAL SEVEN
    "\xe2\x85\xb7" => "\xe2\x85\xa7", // SMALL ROMAN NUMERAL EIGHT
    "\xe2\x85\xb8" => "\xe2\x85\xa8", // SMALL ROMAN NUMERAL NINE
    "\xe2\x85\xb9" => "\xe2\x85\xa9", // SMALL ROMAN NUMERAL TEN
    "\xe2\x85\xba" => "\xe2\x85\xaa", // SMALL ROMAN NUMERAL ELEVEN
    "\xe2\x85\xbb" => "\xe2\x85\xab", // SMALL ROMAN NUMERAL TWELVE
    "\xe2\x85\xbc" => "\xe2\x85\xac", // SMALL ROMAN NUMERAL FIFTY
    "\xe2\x85\xbd" => "\xe2\x85\xad", // SMALL ROMAN NUMERAL ONE HUNDRED
    "\xe2\x85\xbe" => "\xe2\x85\xae", // SMALL ROMAN NUMERAL FIVE HUNDRED
    "\xe2\x85\xbf" => "\xe2\x85\xaf", // SMALL ROMAN NUMERAL ONE THOUSAND
    "\xe2\x86\x84" => "\xe2\x86\x83", // LATIN SMALL LETTER REVERSED C
    "\xe2\x93\x90" => "\xe2\x92\xb6", // CIRCLED LATIN SMALL LETTER A
    "\xe2\x93\x91" => "\xe2\x92\xb7", // CIRCLED LATIN SMALL LETTER B
    "\xe2\x93\x92" => "\xe2\x92\xb8", // CIRCLED LATIN SMALL LETTER C
    "\xe2\x93\x93" => "\xe2\x92\xb9", // CIRCLED LATIN SMALL LETTER D
    "\xe2\x93\x94" => "\xe2\x92\xba", // CIRCLED LATIN SMALL LETTER E
    "\xe2\x93\x95" => "\xe2\x92\xbb", // CIRCLED LATIN SMALL LETTER F
    "\xe2\x93\x96" => "\xe2\x92\xbc", // CIRCLED LATIN SMALL LETTER G
    "\xe2\x93\x97" => "\xe2\x92\xbd", // CIRCLED LATIN SMALL LETTER H
    "\xe2\x93\x98" => "\xe2\x92\xbe", // CIRCLED LATIN SMALL LETTER I
    "\xe2\x93\x99" => "\xe2\x92\xbf", // CIRCLED LATIN SMALL LETTER J
    "\xe2\x93\x9a" => "\xe2\x93\x80", // CIRCLED LATIN SMALL LETTER K
    "\xe2\x93\x9b" => "\xe2\x93\x81", // CIRCLED LATIN SMALL LETTER L
    "\xe2\x93\x9c" => "\xe2\x93\x82", // CIRCLED LATIN SMALL LETTER M
    "\xe2\x93\x9d" => "\xe2\x93\x83", // CIRCLED LATIN SMALL LETTER N
    "\xe2\x93\x9e" => "\xe2\x93\x84", // CIRCLED LATIN SMALL LETTER O
    "\xe2\x93\x9f" => "\xe2\x93\x85", // CIRCLED LATIN SMALL LETTER P
    "\xe2\x93\xa0" => "\xe2\x93\x86", // CIRCLED LATIN SMALL LETTER Q
    "\xe2\x93\xa1" => "\xe2\x93\x87", // CIRCLED LATIN SMALL LETTER R
    "\xe2\x93\xa2" => "\xe2\x93\x88", // CIRCLED LATIN SMALL LETTER S
    "\xe2\x93\xa3" => "\xe2\x93\x89", // CIRCLED LATIN SMALL LETTER T
    "\xe2\x93\xa4" => "\xe2\x93\x8a", // CIRCLED LATIN SMALL LETTER U
    "\xe2\x93\xa5" => "\xe2\x93\x8b", // CIRCLED LATIN SMALL LETTER V
    "\xe2\x93\xa6" => "\xe2\x93\x8c", // CIRCLED LATIN SMALL LETTER W
    "\xe2\x93\xa7" => "\xe2\x93\x8d", // CIRCLED LATIN SMALL LETTER X
    "\xe2\x93\xa8" => "\xe2\x93\x8e", // CIRCLED LATIN SMALL LETTER Y
    "\xe2\x93\xa9" => "\xe2\x93\x8f", // CIRCLED LATIN SMALL LETTER Z
    "\xe2\xb0\xb0" => "\xe2\xb0\x80", // GLAGOLITIC SMALL LETTER AZU
    "\xe2\xb0\xb1" => "\xe2\xb0\x81", // GLAGOLITIC SMALL LETTER BUKY
    "\xe2\xb0\xb2" => "\xe2\xb0\x82", // GLAGOLITIC SMALL LETTER VEDE
    "\xe2\xb0\xb3" => "\xe2\xb0\x83", // GLAGOLITIC SMALL LETTER GLAGOLI
    "\xe2\xb0\xb4" => "\xe2\xb0\x84", // GLAGOLITIC SMALL LETTER DOBRO
    "\xe2\xb0\xb5" => "\xe2\xb0\x85", // GLAGOLITIC SMALL LETTER YESTU
    "\xe2\xb0\xb6" => "\xe2\xb0\x86", // GLAGOLITIC SMALL LETTER ZHIVETE
    "\xe2\xb0\xb7" => "\xe2\xb0\x87", // GLAGOLITIC SMALL LETTER DZELO
    "\xe2\xb0\xb8" => "\xe2\xb0\x88", // GLAGOLITIC SMALL LETTER ZEMLJA
    "\xe2\xb0\xb9" => "\xe2\xb0\x89", // GLAGOLITIC SMALL LETTER IZHE
    "\xe2\xb0\xba" => "\xe2\xb0\x8a", // GLAGOLITIC SMALL LETTER INITIAL IZHE
    "\xe2\xb0\xbb" => "\xe2\xb0\x8b", // GLAGOLITIC SMALL LETTER I
    "\xe2\xb0\xbc" => "\xe2\xb0\x8c", // GLAGOLITIC SMALL LETTER DJERVI
    "\xe2\xb0\xbd" => "\xe2\xb0\x8d", // GLAGOLITIC SMALL LETTER KAKO
    "\xe2\xb0\xbe" => "\xe2\xb0\x8e", // GLAGOLITIC SMALL LETTER LJUDIJE
    "\xe2\xb0\xbf" => "\xe2\xb0\x8f", // GLAGOLITIC SMALL LETTER MYSLITE
    "\xe2\xb1\x80" => "\xe2\xb0\x90", // GLAGOLITIC SMALL LETTER NASHI
    "\xe2\xb1\x81" => "\xe2\xb0\x91", // GLAGOLITIC SMALL LETTER ONU
    "\xe2\xb1\x82" => "\xe2\xb0\x92", // GLAGOLITIC SMALL LETTER POKOJI
    "\xe2\xb1\x83" => "\xe2\xb0\x93", // GLAGOLITIC SMALL LETTER RITSI
    "\xe2\xb1\x84" => "\xe2\xb0\x94", // GLAGOLITIC SMALL LETTER SLOVO
    "\xe2\xb1\x85" => "\xe2\xb0\x95", // GLAGOLITIC SMALL LETTER TVRIDO
    "\xe2\xb1\x86" => "\xe2\xb0\x96", // GLAGOLITIC SMALL LETTER UKU
    "\xe2\xb1\x87" => "\xe2\xb0\x97", // GLAGOLITIC SMALL LETTER FRITU
    "\xe2\xb1\x88" => "\xe2\xb0\x98", // GLAGOLITIC SMALL LETTER HERU
    "\xe2\xb1\x89" => "\xe2\xb0\x99", // GLAGOLITIC SMALL LETTER OTU
    "\xe2\xb1\x8a" => "\xe2\xb0\x9a", // GLAGOLITIC SMALL LETTER PE
    "\xe2\xb1\x8b" => "\xe2\xb0\x9b", // GLAGOLITIC SMALL LETTER SHTA
    "\xe2\xb1\x8c" => "\xe2\xb0\x9c", // GLAGOLITIC SMALL LETTER TSI
    "\xe2\xb1\x8d" => "\xe2\xb0\x9d", // GLAGOLITIC SMALL LETTER CHRIVI
    "\xe2\xb1\x8e" => "\xe2\xb0\x9e", // GLAGOLITIC SMALL LETTER SHA
    "\xe2\xb1\x8f" => "\xe2\xb0\x9f", // GLAGOLITIC SMALL LETTER YERU
    "\xe2\xb1\x90" => "\xe2\xb0\xa0", // GLAGOLITIC SMALL LETTER YERI
    "\xe2\xb1\x91" => "\xe2\xb0\xa1", // GLAGOLITIC SMALL LETTER YATI
    "\xe2\xb1\x92" => "\xe2\xb0\xa2", // GLAGOLITIC SMALL LETTER SPIDERY HA
    "\xe2\xb1\x93" => "\xe2\xb0\xa3", // GLAGOLITIC SMALL LETTER YU
    "\xe2\xb1\x94" => "\xe2\xb0\xa4", // GLAGOLITIC SMALL LETTER SMALL YUS
    "\xe2\xb1\x95" => "\xe2\xb0\xa5", // GLAGOLITIC SMALL LETTER SMALL YUS WITH TAIL
    "\xe2\xb1\x96" => "\xe2\xb0\xa6", // GLAGOLITIC SMALL LETTER YO
    "\xe2\xb1\x97" => "\xe2\xb0\xa7", // GLAGOLITIC SMALL LETTER IOTATED SMALL YUS
    "\xe2\xb1\x98" => "\xe2\xb0\xa8", // GLAGOLITIC SMALL LETTER BIG YUS
    "\xe2\xb1\x99" => "\xe2\xb0\xa9", // GLAGOLITIC SMALL LETTER IOTATED BIG YUS
    "\xe2\xb1\x9a" => "\xe2\xb0\xaa", // GLAGOLITIC SMALL LETTER FITA
    "\xe2\xb1\x9b" => "\xe2\xb0\xab", // GLAGOLITIC SMALL LETTER IZHITSA
    "\xe2\xb1\x9c" => "\xe2\xb0\xac", // GLAGOLITIC SMALL LETTER SHTAPIC
    "\xe2\xb1\x9d" => "\xe2\xb0\xad", // GLAGOLITIC SMALL LETTER TROKUTASTI A
    "\xe2\xb1\x9e" => "\xe2\xb0\xae", // GLAGOLITIC SMALL LETTER LATINATE MYSLITE
    "\xe2\xb1\xa1" => "\xe2\xb1\xa0", // LATIN SMALL LETTER L WITH DOUBLE BAR
    "\xe2\xb1\xa5" => "\xc8\xba", // LATIN SMALL LETTER A WITH STROKE
    "\xe2\xb1\xa6" => "\xc8\xbe", // LATIN SMALL LETTER T WITH DIAGONAL STROKE
    "\xe2\xb1\xa8" => "\xe2\xb1\xa7", // LATIN SMALL LETTER H WITH DESCENDER
    "\xe2\xb1\xaa" => "\xe2\xb1\xa9", // LATIN SMALL LETTER K WITH DESCENDER
    "\xe2\xb1\xac" => "\xe2\xb1\xab", // LATIN SMALL LETTER Z WITH DESCENDER
    "\xe2\xb1\xb3" => "\xe2\xb1\xb2", // LATIN SMALL LETTER W WITH HOOK
    "\xe2\xb1\xb6" => "\xe2\xb1\xb5", // LATIN SMALL LETTER HALF H
    "\xe2\xb2\x81" => "\xe2\xb2\x80", // COPTIC SMALL LETTER ALFA
    "\xe2\xb2\x83" => "\xe2\xb2\x82", // COPTIC SMALL LETTER VIDA
    "\xe2\xb2\x85" => "\xe2\xb2\x84", // COPTIC SMALL LETTER GAMMA
    "\xe2\xb2\x87" => "\xe2\xb2\x86", // COPTIC SMALL LETTER DALDA
    "\xe2\xb2\x89" => "\xe2\xb2\x88", // COPTIC SMALL LETTER EIE
    "\xe2\xb2\x8b" => "\xe2\xb2\x8a", // COPTIC SMALL LETTER SOU
    "\xe2\xb2\x8d" => "\xe2\xb2\x8c", // COPTIC SMALL LETTER ZATA
    "\xe2\xb2\x8f" => "\xe2\xb2\x8e", // COPTIC SMALL LETTER HATE
    "\xe2\xb2\x91" => "\xe2\xb2\x90", // COPTIC SMALL LETTER THETHE
    "\xe2\xb2\x93" => "\xe2\xb2\x92", // COPTIC SMALL LETTER IAUDA
    "\xe2\xb2\x95" => "\xe2\xb2\x94", // COPTIC SMALL LETTER KAPA
    "\xe2\xb2\x97" => "\xe2\xb2\x96", // COPTIC SMALL LETTER LAULA
    "\xe2\xb2\x99" => "\xe2\xb2\x98", // COPTIC SMALL LETTER MI
    "\xe2\xb2\x9b" => "\xe2\xb2\x9a", // COPTIC SMALL LETTER NI
    "\xe2\xb2\x9d" => "\xe2\xb2\x9c", // COPTIC SMALL LETTER KSI
    "\xe2\xb2\x9f" => "\xe2\xb2\x9e", // COPTIC SMALL LETTER O
    "\xe2\xb2\xa1" => "\xe2\xb2\xa0", // COPTIC SMALL LETTER PI
    "\xe2\xb2\xa3" => "\xe2\xb2\xa2", // COPTIC SMALL LETTER RO
    "\xe2\xb2\xa5" => "\xe2\xb2\xa4", // COPTIC SMALL LETTER SIMA
    "\xe2\xb2\xa7" => "\xe2\xb2\xa6", // COPTIC SMALL LETTER TAU
    "\xe2\xb2\xa9" => "\xe2\xb2\xa8", // COPTIC SMALL LETTER UA
    "\xe2\xb2\xab" => "\xe2\xb2\xaa", // COPTIC SMALL LETTER FI
    "\xe2\xb2\xad" => "\xe2\xb2\xac", // COPTIC SMALL LETTER KHI
    "\xe2\xb2\xaf" => "\xe2\xb2\xae", // COPTIC SMALL LETTER PSI
    "\xe2\xb2\xb1" => "\xe2\xb2\xb0", // COPTIC SMALL LETTER OOU
    "\xe2\xb2\xb3" => "\xe2\xb2\xb2", // COPTIC SMALL LETTER DIALECT-P ALEF
    "\xe2\xb2\xb5" => "\xe2\xb2\xb4", // COPTIC SMALL LETTER OLD COPTIC AIN
    "\xe2\xb2\xb7" => "\xe2\xb2\xb6", // COPTIC SMALL LETTER CRYPTOGRAMMIC EIE
    "\xe2\xb2\xb9" => "\xe2\xb2\xb8", // COPTIC SMALL LETTER DIALECT-P KAPA
    "\xe2\xb2\xbb" => "\xe2\xb2\xba", // COPTIC SMALL LETTER DIALECT-P NI
    "\xe2\xb2\xbd" => "\xe2\xb2\xbc", // COPTIC SMALL LETTER CRYPTOGRAMMIC NI
    "\xe2\xb2\xbf" => "\xe2\xb2\xbe", // COPTIC SMALL LETTER OLD COPTIC OOU
    "\xe2\xb3\x81" => "\xe2\xb3\x80", // COPTIC SMALL LETTER SAMPI
    "\xe2\xb3\x83" => "\xe2\xb3\x82", // COPTIC SMALL LETTER CROSSED SHEI
    "\xe2\xb3\x85" => "\xe2\xb3\x84", // COPTIC SMALL LETTER OLD COPTIC SHEI
    "\xe2\xb3\x87" => "\xe2\xb3\x86", // COPTIC SMALL LETTER OLD COPTIC ESH
    "\xe2\xb3\x89" => "\xe2\xb3\x88", // COPTIC SMALL LETTER AKHMIMIC KHEI
    "\xe2\xb3\x8b" => "\xe2\xb3\x8a", // COPTIC SMALL LETTER DIALECT-P HORI
    "\xe2\xb3\x8d" => "\xe2\xb3\x8c", // COPTIC SMALL LETTER OLD COPTIC HORI
    "\xe2\xb3\x8f" => "\xe2\xb3\x8e", // COPTIC SMALL LETTER OLD COPTIC HA
    "\xe2\xb3\x91" => "\xe2\xb3\x90", // COPTIC SMALL LETTER L-SHAPED HA
    "\xe2\xb3\x93" => "\xe2\xb3\x92", // COPTIC SMALL LETTER OLD COPTIC HEI
    "\xe2\xb3\x95" => "\xe2\xb3\x94", // COPTIC SMALL LETTER OLD COPTIC HAT
    "\xe2\xb3\x97" => "\xe2\xb3\x96", // COPTIC SMALL LETTER OLD COPTIC GANGIA
    "\xe2\xb3\x99" => "\xe2\xb3\x98", // COPTIC SMALL LETTER OLD COPTIC DJA
    "\xe2\xb3\x9b" => "\xe2\xb3\x9a", // COPTIC SMALL LETTER OLD COPTIC SHIMA
    "\xe2\xb3\x9d" => "\xe2\xb3\x9c", // COPTIC SMALL LETTER OLD NUBIAN SHIMA
    "\xe2\xb3\x9f" => "\xe2\xb3\x9e", // COPTIC SMALL LETTER OLD NUBIAN NGI
    "\xe2\xb3\xa1" => "\xe2\xb3\xa0", // COPTIC SMALL LETTER OLD NUBIAN NYI
    "\xe2\xb3\xa3" => "\xe2\xb3\xa2", // COPTIC SMALL LETTER OLD NUBIAN WAU
    "\xe2\xb3\xac" => "\xe2\xb3\xab", // COPTIC SMALL LETTER CRYPTOGRAMMIC SHEI
    "\xe2\xb3\xae" => "\xe2\xb3\xad", // COPTIC SMALL LETTER CRYPTOGRAMMIC GANGIA
    "\xe2\xb4\x80" => "\xe1\x82\xa0", // GEORGIAN SMALL LETTER AN
    "\xe2\xb4\x81" => "\xe1\x82\xa1", // GEORGIAN SMALL LETTER BAN
    "\xe2\xb4\x82" => "\xe1\x82\xa2", // GEORGIAN SMALL LETTER GAN
    "\xe2\xb4\x83" => "\xe1\x82\xa3", // GEORGIAN SMALL LETTER DON
    "\xe2\xb4\x84" => "\xe1\x82\xa4", // GEORGIAN SMALL LETTER EN
    "\xe2\xb4\x85" => "\xe1\x82\xa5", // GEORGIAN SMALL LETTER VIN
    "\xe2\xb4\x86" => "\xe1\x82\xa6", // GEORGIAN SMALL LETTER ZEN
    "\xe2\xb4\x87" => "\xe1\x82\xa7", // GEORGIAN SMALL LETTER TAN
    "\xe2\xb4\x88" => "\xe1\x82\xa8", // GEORGIAN SMALL LETTER IN
    "\xe2\xb4\x89" => "\xe1\x82\xa9", // GEORGIAN SMALL LETTER KAN
    "\xe2\xb4\x8a" => "\xe1\x82\xaa", // GEORGIAN SMALL LETTER LAS
    "\xe2\xb4\x8b" => "\xe1\x82\xab", // GEORGIAN SMALL LETTER MAN
    "\xe2\xb4\x8c" => "\xe1\x82\xac", // GEORGIAN SMALL LETTER NAR
    "\xe2\xb4\x8d" => "\xe1\x82\xad", // GEORGIAN SMALL LETTER ON
    "\xe2\xb4\x8e" => "\xe1\x82\xae", // GEORGIAN SMALL LETTER PAR
    "\xe2\xb4\x8f" => "\xe1\x82\xaf", // GEORGIAN SMALL LETTER ZHAR
    "\xe2\xb4\x90" => "\xe1\x82\xb0", // GEORGIAN SMALL LETTER RAE
    "\xe2\xb4\x91" => "\xe1\x82\xb1", // GEORGIAN SMALL LETTER SAN
    "\xe2\xb4\x92" => "\xe1\x82\xb2", // GEORGIAN SMALL LETTER TAR
    "\xe2\xb4\x93" => "\xe1\x82\xb3", // GEORGIAN SMALL LETTER UN
    "\xe2\xb4\x94" => "\xe1\x82\xb4", // GEORGIAN SMALL LETTER PHAR
    "\xe2\xb4\x95" => "\xe1\x82\xb5", // GEORGIAN SMALL LETTER KHAR
    "\xe2\xb4\x96" => "\xe1\x82\xb6", // GEORGIAN SMALL LETTER GHAN
    "\xe2\xb4\x97" => "\xe1\x82\xb7", // GEORGIAN SMALL LETTER QAR
    "\xe2\xb4\x98" => "\xe1\x82\xb8", // GEORGIAN SMALL LETTER SHIN
    "\xe2\xb4\x99" => "\xe1\x82\xb9", // GEORGIAN SMALL LETTER CHIN
    "\xe2\xb4\x9a" => "\xe1\x82\xba", // GEORGIAN SMALL LETTER CAN
    "\xe2\xb4\x9b" => "\xe1\x82\xbb", // GEORGIAN SMALL LETTER JIL
    "\xe2\xb4\x9c" => "\xe1\x82\xbc", // GEORGIAN SMALL LETTER CIL
    "\xe2\xb4\x9d" => "\xe1\x82\xbd", // GEORGIAN SMALL LETTER CHAR
    "\xe2\xb4\x9e" => "\xe1\x82\xbe", // GEORGIAN SMALL LETTER XAN
    "\xe2\xb4\x9f" => "\xe1\x82\xbf", // GEORGIAN SMALL LETTER JHAN
    "\xe2\xb4\xa0" => "\xe1\x83\x80", // GEORGIAN SMALL LETTER HAE
    "\xe2\xb4\xa1" => "\xe1\x83\x81", // GEORGIAN SMALL LETTER HE
    "\xe2\xb4\xa2" => "\xe1\x83\x82", // GEORGIAN SMALL LETTER HIE
    "\xe2\xb4\xa3" => "\xe1\x83\x83", // GEORGIAN SMALL LETTER WE
    "\xe2\xb4\xa4" => "\xe1\x83\x84", // GEORGIAN SMALL LETTER HAR
    "\xe2\xb4\xa5" => "\xe1\x83\x85", // GEORGIAN SMALL LETTER HOE
    "\xea\x99\x81" => "\xea\x99\x80", // CYRILLIC SMALL LETTER ZEMLYA
    "\xea\x99\x83" => "\xea\x99\x82", // CYRILLIC SMALL LETTER DZELO
    "\xea\x99\x85" => "\xea\x99\x84", // CYRILLIC SMALL LETTER REVERSED DZE
    "\xea\x99\x87" => "\xea\x99\x86", // CYRILLIC SMALL LETTER IOTA
    "\xea\x99\x89" => "\xea\x99\x88", // CYRILLIC SMALL LETTER DJERV
    "\xea\x99\x8b" => "\xea\x99\x8a", // CYRILLIC SMALL LETTER MONOGRAPH UK
    "\xea\x99\x8d" => "\xea\x99\x8c", // CYRILLIC SMALL LETTER BROAD OMEGA
    "\xea\x99\x8f" => "\xea\x99\x8e", // CYRILLIC SMALL LETTER NEUTRAL YER
    "\xea\x99\x91" => "\xea\x99\x90", // CYRILLIC SMALL LETTER YERU WITH BACK YER
    "\xea\x99\x93" => "\xea\x99\x92", // CYRILLIC SMALL LETTER IOTIFIED YAT
    "\xea\x99\x95" => "\xea\x99\x94", // CYRILLIC SMALL LETTER REVERSED YU
    "\xea\x99\x97" => "\xea\x99\x96", // CYRILLIC SMALL LETTER IOTIFIED A
    "\xea\x99\x99" => "\xea\x99\x98", // CYRILLIC SMALL LETTER CLOSED LITTLE YUS
    "\xea\x99\x9b" => "\xea\x99\x9a", // CYRILLIC SMALL LETTER BLENDED YUS
    "\xea\x99\x9d" => "\xea\x99\x9c", // CYRILLIC SMALL LETTER IOTIFIED CLOSED LITTLE YUS
    "\xea\x99\x9f" => "\xea\x99\x9e", // CYRILLIC SMALL LETTER YN
    "\xea\x99\xa1" => "\xea\x99\xa0", // CYRILLIC SMALL LETTER REVERSED TSE
    "\xea\x99\xa3" => "\xea\x99\xa2", // CYRILLIC SMALL LETTER SOFT DE
    "\xea\x99\xa5" => "\xea\x99\xa4", // CYRILLIC SMALL LETTER SOFT EL
    "\xea\x99\xa7" => "\xea\x99\xa6", // CYRILLIC SMALL LETTER SOFT EM
    "\xea\x99\xa9" => "\xea\x99\xa8", // CYRILLIC SMALL LETTER MONOCULAR O
    "\xea\x99\xab" => "\xea\x99\xaa", // CYRILLIC SMALL LETTER BINOCULAR O
    "\xea\x99\xad" => "\xea\x99\xac", // CYRILLIC SMALL LETTER DOUBLE MONOCULAR O
    "\xea\x9a\x81" => "\xea\x9a\x80", // CYRILLIC SMALL LETTER DWE
    "\xea\x9a\x83" => "\xea\x9a\x82", // CYRILLIC SMALL LETTER DZWE
    "\xea\x9a\x85" => "\xea\x9a\x84", // CYRILLIC SMALL LETTER ZHWE
    "\xea\x9a\x87" => "\xea\x9a\x86", // CYRILLIC SMALL LETTER CCHE
    "\xea\x9a\x89" => "\xea\x9a\x88", // CYRILLIC SMALL LETTER DZZE
    "\xea\x9a\x8b" => "\xea\x9a\x8a", // CYRILLIC SMALL LETTER TE WITH MIDDLE HOOK
    "\xea\x9a\x8d" => "\xea\x9a\x8c", // CYRILLIC SMALL LETTER TWE
    "\xea\x9a\x8f" => "\xea\x9a\x8e", // CYRILLIC SMALL LETTER TSWE
    "\xea\x9a\x91" => "\xea\x9a\x90", // CYRILLIC SMALL LETTER TSSE
    "\xea\x9a\x93" => "\xea\x9a\x92", // CYRILLIC SMALL LETTER TCHE
    "\xea\x9a\x95" => "\xea\x9a\x94", // CYRILLIC SMALL LETTER HWE
    "\xea\x9a\x97" => "\xea\x9a\x96", // CYRILLIC SMALL LETTER SHWE
    "\xea\x9c\xa3" => "\xea\x9c\xa2", // LATIN SMALL LETTER EGYPTOLOGICAL ALEF
    "\xea\x9c\xa5" => "\xea\x9c\xa4", // LATIN SMALL LETTER EGYPTOLOGICAL AIN
    "\xea\x9c\xa7" => "\xea\x9c\xa6", // LATIN SMALL LETTER HENG
    "\xea\x9c\xa9" => "\xea\x9c\xa8", // LATIN SMALL LETTER TZ
    "\xea\x9c\xab" => "\xea\x9c\xaa", // LATIN SMALL LETTER TRESILLO
    "\xea\x9c\xad" => "\xea\x9c\xac", // LATIN SMALL LETTER CUATRILLO
    "\xea\x9c\xaf" => "\xea\x9c\xae", // LATIN SMALL LETTER CUATRILLO WITH COMMA
    "\xea\x9c\xb3" => "\xea\x9c\xb2", // LATIN SMALL LETTER AA
    "\xea\x9c\xb5" => "\xea\x9c\xb4", // LATIN SMALL LETTER AO
    "\xea\x9c\xb7" => "\xea\x9c\xb6", // LATIN SMALL LETTER AU
    "\xea\x9c\xb9" => "\xea\x9c\xb8", // LATIN SMALL LETTER AV
    "\xea\x9c\xbb" => "\xea\x9c\xba", // LATIN SMALL LETTER AV WITH HORIZONTAL BAR
    "\xea\x9c\xbd" => "\xea\x9c\xbc", // LATIN SMALL LETTER AY
    "\xea\x9c\xbf" => "\xea\x9c\xbe", // LATIN SMALL LETTER REVERSED C WITH DOT
    "\xea\x9d\x81" => "\xea\x9d\x80", // LATIN SMALL LETTER K WITH STROKE
    "\xea\x9d\x83" => "\xea\x9d\x82", // LATIN SMALL LETTER K WITH DIAGONAL STROKE
    "\xea\x9d\x85" => "\xea\x9d\x84", // LATIN SMALL LETTER K WITH STROKE AND DIAGONAL STROKE
    "\xea\x9d\x87" => "\xea\x9d\x86", // LATIN SMALL LETTER BROKEN L
    "\xea\x9d\x89" => "\xea\x9d\x88", // LATIN SMALL LETTER L WITH HIGH STROKE
    "\xea\x9d\x8b" => "\xea\x9d\x8a", // LATIN SMALL LETTER O WITH LONG STROKE OVERLAY
    "\xea\x9d\x8d" => "\xea\x9d\x8c", // LATIN SMALL LETTER O WITH LOOP
    "\xea\x9d\x8f" => "\xea\x9d\x8e", // LATIN SMALL LETTER OO
    "\xea\x9d\x91" => "\xea\x9d\x90", // LATIN SMALL LETTER P WITH STROKE THROUGH DESCENDER
    "\xea\x9d\x93" => "\xea\x9d\x92", // LATIN SMALL LETTER P WITH FLOURISH
    "\xea\x9d\x95" => "\xea\x9d\x94", // LATIN SMALL LETTER P WITH SQUIRREL TAIL
    "\xea\x9d\x97" => "\xea\x9d\x96", // LATIN SMALL LETTER Q WITH STROKE THROUGH DESCENDER
    "\xea\x9d\x99" => "\xea\x9d\x98", // LATIN SMALL LETTER Q WITH DIAGONAL STROKE
    "\xea\x9d\x9b" => "\xea\x9d\x9a", // LATIN SMALL LETTER R ROTUNDA
    "\xea\x9d\x9d" => "\xea\x9d\x9c", // LATIN SMALL LETTER RUM ROTUNDA
    "\xea\x9d\x9f" => "\xea\x9d\x9e", // LATIN SMALL LETTER V WITH DIAGONAL STROKE
    "\xea\x9d\xa1" => "\xea\x9d\xa0", // LATIN SMALL LETTER VY
    "\xea\x9d\xa3" => "\xea\x9d\xa2", // LATIN SMALL LETTER VISIGOTHIC Z
    "\xea\x9d\xa5" => "\xea\x9d\xa4", // LATIN SMALL LETTER THORN WITH STROKE
    "\xea\x9d\xa7" => "\xea\x9d\xa6", // LATIN SMALL LETTER THORN WITH STROKE THROUGH DESCENDER
    "\xea\x9d\xa9" => "\xea\x9d\xa8", // LATIN SMALL LETTER VEND
    "\xea\x9d\xab" => "\xea\x9d\xaa", // LATIN SMALL LETTER ET
    "\xea\x9d\xad" => "\xea\x9d\xac", // LATIN SMALL LETTER IS
    "\xea\x9d\xaf" => "\xea\x9d\xae", // LATIN SMALL LETTER CON
    "\xea\x9d\xba" => "\xea\x9d\xb9", // LATIN SMALL LETTER INSULAR D
    "\xea\x9d\xbc" => "\xea\x9d\xbb", // LATIN SMALL LETTER INSULAR F
    "\xea\x9d\xbf" => "\xea\x9d\xbe", // LATIN SMALL LETTER TURNED INSULAR G
    "\xea\x9e\x81" => "\xea\x9e\x80", // LATIN SMALL LETTER TURNED L
    "\xea\x9e\x83" => "\xea\x9e\x82", // LATIN SMALL LETTER INSULAR R
    "\xea\x9e\x85" => "\xea\x9e\x84", // LATIN SMALL LETTER INSULAR S
    "\xea\x9e\x87" => "\xea\x9e\x86", // LATIN SMALL LETTER INSULAR T
    "\xea\x9e\x8c" => "\xea\x9e\x8b", // LATIN SMALL LETTER SALTILLO
    "\xea\x9e\x91" => "\xea\x9e\x90", // LATIN SMALL LETTER N WITH DESCENDER
    "\xea\x9e\xa1" => "\xea\x9e\xa0", // LATIN SMALL LETTER G WITH OBLIQUE STROKE
    "\xea\x9e\xa3" => "\xea\x9e\xa2", // LATIN SMALL LETTER K WITH OBLIQUE STROKE
    "\xea\x9e\xa5" => "\xea\x9e\xa4", // LATIN SMALL LETTER N WITH OBLIQUE STROKE
    "\xea\x9e\xa7" => "\xea\x9e\xa6", // LATIN SMALL LETTER R WITH OBLIQUE STROKE
    "\xea\x9e\xa9" => "\xea\x9e\xa8", // LATIN SMALL LETTER S WITH OBLIQUE STROKE
    "\xef\xbd\x81" => "\xef\xbc\xa1", // FULLWIDTH LATIN SMALL LETTER A
    "\xef\xbd\x82" => "\xef\xbc\xa2", // FULLWIDTH LATIN SMALL LETTER B
    "\xef\xbd\x83" => "\xef\xbc\xa3", // FULLWIDTH LATIN SMALL LETTER C
    "\xef\xbd\x84" => "\xef\xbc\xa4", // FULLWIDTH LATIN SMALL LETTER D
    "\xef\xbd\x85" => "\xef\xbc\xa5", // FULLWIDTH LATIN SMALL LETTER E
    "\xef\xbd\x86" => "\xef\xbc\xa6", // FULLWIDTH LATIN SMALL LETTER F
    "\xef\xbd\x87" => "\xef\xbc\xa7", // FULLWIDTH LATIN SMALL LETTER G
    "\xef\xbd\x88" => "\xef\xbc\xa8", // FULLWIDTH LATIN SMALL LETTER H
    "\xef\xbd\x89" => "\xef\xbc\xa9", // FULLWIDTH LATIN SMALL LETTER I
    "\xef\xbd\x8a" => "\xef\xbc\xaa", // FULLWIDTH LATIN SMALL LETTER J
    "\xef\xbd\x8b" => "\xef\xbc\xab", // FULLWIDTH LATIN SMALL LETTER K
    "\xef\xbd\x8c" => "\xef\xbc\xac", // FULLWIDTH LATIN SMALL LETTER L
    "\xef\xbd\x8d" => "\xef\xbc\xad", // FULLWIDTH LATIN SMALL LETTER M
    "\xef\xbd\x8e" => "\xef\xbc\xae", // FULLWIDTH LATIN SMALL LETTER N
    "\xef\xbd\x8f" => "\xef\xbc\xaf", // FULLWIDTH LATIN SMALL LETTER O
    "\xef\xbd\x90" => "\xef\xbc\xb0", // FULLWIDTH LATIN SMALL LETTER P
    "\xef\xbd\x91" => "\xef\xbc\xb1", // FULLWIDTH LATIN SMALL LETTER Q
    "\xef\xbd\x92" => "\xef\xbc\xb2", // FULLWIDTH LATIN SMALL LETTER R
    "\xef\xbd\x93" => "\xef\xbc\xb3", // FULLWIDTH LATIN SMALL LETTER S
    "\xef\xbd\x94" => "\xef\xbc\xb4", // FULLWIDTH LATIN SMALL LETTER T
    "\xef\xbd\x95" => "\xef\xbc\xb5", // FULLWIDTH LATIN SMALL LETTER U
    "\xef\xbd\x96" => "\xef\xbc\xb6", // FULLWIDTH LATIN SMALL LETTER V
    "\xef\xbd\x97" => "\xef\xbc\xb7", // FULLWIDTH LATIN SMALL LETTER W
    "\xef\xbd\x98" => "\xef\xbc\xb8", // FULLWIDTH LATIN SMALL LETTER X
    "\xef\xbd\x99" => "\xef\xbc\xb9", // FULLWIDTH LATIN SMALL LETTER Y
    "\xef\xbd\x9a" => "\xef\xbc\xba", // FULLWIDTH LATIN SMALL LETTER Z
    "\xf0\x90\x90\xa8" => "\xf0\x90\x90\x80", // DESERET SMALL LETTER LONG I
    "\xf0\x90\x90\xa9" => "\xf0\x90\x90\x81", // DESERET SMALL LETTER LONG E
    "\xf0\x90\x90\xaa" => "\xf0\x90\x90\x82", // DESERET SMALL LETTER LONG A
    "\xf0\x90\x90\xab" => "\xf0\x90\x90\x83", // DESERET SMALL LETTER LONG AH
    "\xf0\x90\x90\xac" => "\xf0\x90\x90\x84", // DESERET SMALL LETTER LONG O
    "\xf0\x90\x90\xad" => "\xf0\x90\x90\x85", // DESERET SMALL LETTER LONG OO
    "\xf0\x90\x90\xae" => "\xf0\x90\x90\x86", // DESERET SMALL LETTER SHORT I
    "\xf0\x90\x90\xaf" => "\xf0\x90\x90\x87", // DESERET SMALL LETTER SHORT E
    "\xf0\x90\x90\xb0" => "\xf0\x90\x90\x88", // DESERET SMALL LETTER SHORT A
    "\xf0\x90\x90\xb1" => "\xf0\x90\x90\x89", // DESERET SMALL LETTER SHORT AH
    "\xf0\x90\x90\xb2" => "\xf0\x90\x90\x8a", // DESERET SMALL LETTER SHORT O
    "\xf0\x90\x90\xb3" => "\xf0\x90\x90\x8b", // DESERET SMALL LETTER SHORT OO
    "\xf0\x90\x90\xb4" => "\xf0\x90\x90\x8c", // DESERET SMALL LETTER AY
    "\xf0\x90\x90\xb5" => "\xf0\x90\x90\x8d", // DESERET SMALL LETTER OW
    "\xf0\x90\x90\xb6" => "\xf0\x90\x90\x8e", // DESERET SMALL LETTER WU
    "\xf0\x90\x90\xb7" => "\xf0\x90\x90\x8f", // DESERET SMALL LETTER YEE
    "\xf0\x90\x90\xb8" => "\xf0\x90\x90\x90", // DESERET SMALL LETTER H
    "\xf0\x90\x90\xb9" => "\xf0\x90\x90\x91", // DESERET SMALL LETTER PEE
    "\xf0\x90\x90\xba" => "\xf0\x90\x90\x92", // DESERET SMALL LETTER BEE
    "\xf0\x90\x90\xbb" => "\xf0\x90\x90\x93", // DESERET SMALL LETTER TEE
    "\xf0\x90\x90\xbc" => "\xf0\x90\x90\x94", // DESERET SMALL LETTER DEE
    "\xf0\x90\x90\xbd" => "\xf0\x90\x90\x95", // DESERET SMALL LETTER CHEE
    "\xf0\x90\x90\xbe" => "\xf0\x90\x90\x96", // DESERET SMALL LETTER JEE
    "\xf0\x90\x90\xbf" => "\xf0\x90\x90\x97", // DESERET SMALL LETTER KAY
    "\xf0\x90\x91\x80" => "\xf0\x90\x90\x98", // DESERET SMALL LETTER GAY
    "\xf0\x90\x91\x81" => "\xf0\x90\x90\x99", // DESERET SMALL LETTER EF
    "\xf0\x90\x91\x82" => "\xf0\x90\x90\x9a", // DESERET SMALL LETTER VEE
    "\xf0\x90\x91\x83" => "\xf0\x90\x90\x9b", // DESERET SMALL LETTER ETH
    "\xf0\x90\x91\x84" => "\xf0\x90\x90\x9c", // DESERET SMALL LETTER THEE
    "\xf0\x90\x91\x85" => "\xf0\x90\x90\x9d", // DESERET SMALL LETTER ES
    "\xf0\x90\x91\x86" => "\xf0\x90\x90\x9e", // DESERET SMALL LETTER ZEE
    "\xf0\x90\x91\x87" => "\xf0\x90\x90\x9f", // DESERET SMALL LETTER ESH
    "\xf0\x90\x91\x88" => "\xf0\x90\x90\xa0", // DESERET SMALL LETTER ZHEE
    "\xf0\x90\x91\x89" => "\xf0\x90\x90\xa1", // DESERET SMALL LETTER ER
    "\xf0\x90\x91\x8a" => "\xf0\x90\x90\xa2", // DESERET SMALL LETTER EL
    "\xf0\x90\x91\x8b" => "\xf0\x90\x90\xa3", // DESERET SMALL LETTER EM
    "\xf0\x90\x91\x8c" => "\xf0\x90\x90\xa4", // DESERET SMALL LETTER EN
    "\xf0\x90\x91\x8d" => "\xf0\x90\x90\xa5", // DESERET SMALL LETTER ENG
    "\xf0\x90\x91\x8e" => "\xf0\x90\x90\xa6", // DESERET SMALL LETTER OI
    "\xf0\x90\x91\x8f" => "\xf0\x90\x90\xa7", // DESERET SMALL LETTER EW
);
}